### ISSUE TITLE
Modificación de unidad organizacional

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#1]
1. Una vez consultada la unidad nacionalización que no tiene asociado ningún usuario, se modifica la información de la unidad organizacional y no se especifica el nombre de la unidad organizacional.

Genera el siiguiente error:
![image](https://cloud.githubusercontent.com/assets/15740125/14692306/de83f61a-071b-11e6-8a5b-82c01db7dff6.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
Verificado en el ambiente en el cual se solucionaron los hallazgos. http://192.168.1.16:8080/Tuga/menu/menu.jsp

http://prntscr.com/aygl88
