### ISSUE TITLE
EDITAR ALBUM

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#100]
Corregir la tilde en la palabra álbum.

![image](https://cloud.githubusercontent.com/assets/15740125/15049637/ece9c6fe-12b4-11e6-860b-d48a1cd4aa2f.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
corrección verificada.

![image](https://cloud.githubusercontent.com/assets/15740125/15331870/e4bfebfc-1c28-11e6-8f61-5724871d618a.png)
