### ISSUE TITLE
Nombre del álbum con espaciados

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#101]
cuando en el nombre del álbum solo se ingresen caracteres de espaciado, mostrar un mensaje que indique: "El nombre del álbum no es válido".
Ya que actualmente se está generando el siguiente mensaje de error

![image](https://cloud.githubusercontent.com/assets/15740125/15049671/32b72096-12b5-11e6-95f3-3b461fec2092.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
Se esta mostrando el siguiente mensaje:
![image](https://cloud.githubusercontent.com/assets/15740125/15331669/000c1224-1c28-11e6-995d-74548d993912.png)

**Comment by AndresTello** [comment]
resuelto.

se decide dejar la validación solo para cuando se digitan espacios, ya que el nombre del álbum no es obligatorio

**Comment by yisana** [comment]
verificado
![image](https://cloud.githubusercontent.com/assets/15740125/15337277/8adccd4a-1c40-11e6-8067-e091e819a035.png)
