### ISSUE TITLE
Tildes en pantalla Edición de albumes

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#102]
poner las tildes correspondientes

![image](https://cloud.githubusercontent.com/assets/15740125/15049762/a68b858e-12b5-11e6-88ae-0b0237badff9.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
verificado
![image](https://cloud.githubusercontent.com/assets/15740125/15230371/e839097a-185a-11e6-8bed-c6d170101b9f.png)
