### ISSUE TITLE
MENSAJE - VIDEOS

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#103]
REEMPLAZAR "OK", POR "ACEPTAR"

![image](https://cloud.githubusercontent.com/assets/15740125/15050084/517d1074-12b7-11e6-92a5-baa774c0d97e.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
ok.
![image](https://cloud.githubusercontent.com/assets/15740125/15335334/7d3ef4fa-1c37-11e6-99a7-8e5a547c8b97.png)
