### ISSUE TITLE
ARTÍCULOS  - MENSAJE DE VALIDACIÓN DE TITULO

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#104]
Reemplazar en el botón el texto "OK", por "ACEPTAR". Aplica tanto para usuario como para funcionario.

![image](https://cloud.githubusercontent.com/assets/15740125/15057941/118f2c40-12df-11e6-88ce-b102160029ff.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
ok.

![image](https://cloud.githubusercontent.com/assets/15740125/15335224/079aa230-1c37-11e6-8431-b28eb50abe40.png)
