### ISSUE TITLE
ARTICULOS - VALIDACION DETALLE DEL ARTICULO

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#105]
Reemplazar el texto del botón "OK", por "ACEPTAR".
Aplica para usuario administrador y funcionario.

![image](https://cloud.githubusercontent.com/assets/15740125/15057997/5ced6422-12df-11e6-88f6-1bd8cc0dae64.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
verificado.

![image](https://cloud.githubusercontent.com/assets/15740125/15335027/33137424-1c36-11e6-8731-ed9f502252c7.png)
