### ISSUE TITLE
TITULO Y DETALLE DE ARTICULO - CARACTERES ESPACIADO

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#106]
cuando solo se ingrese caracteres de espaciado tanto en el titulo como en el detalle del artículo, se debe mostrar un mensaje indicando que: "El contenido ingresado no es válido".

![image](https://cloud.githubusercontent.com/assets/15740125/15058135/3e2b233e-12e0-11e6-989f-8dc87e298aee.png)

**Comment by AndresTello** [comment]
resuelto.

para el campo descripción del articulo no es posible hacer la validación ya que el editor de texto no lo permite

**Comment by yisana** [comment]
verificado

![image](https://cloud.githubusercontent.com/assets/15740125/15334880/a584eb88-1c35-11e6-8f8e-6f96d039bf17.png)

**Comment by yisana** [comment]
![image](https://cloud.githubusercontent.com/assets/15740125/15334990/0d725456-1c36-11e6-914e-fa2be3d4ba08.png)
