### ISSUE TITLE
Mensajes de correo electrónico Registro de usuario

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#109]
Reemplazar los mensajes que actualmente llegan a los usuarios por medio de un correo electrónico de la siguiente manera:
1. REGISTRO DE USUARIO
   Actualmente el mensaje es el que se muestra en la siguiente imagen:
   ![image](https://cloud.githubusercontent.com/assets/15740125/15074564/5124fc82-1365-11e6-8edd-9cad0224e415.png)

Cambios a realizar:
Debemos colocar:
- El logo de GECO de ser posible en el encabezado.
- UN TITULO QUE DIGA: VALIDACIÓN DE REGISTRO.
- Cuerpo del mensaje: "Hola (Nombre de la persona registrada),
  Hemos recibido su solicitud de registro, para completar el proceso ingrese a este link e indique el siguiente usuario: lcortes y código de seguridad: 28323 

De antemano te damos una cordial bienvenida a GECO."

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
verificado. Ahora se debe ubicar el logo de geco en el encabezado del mensaje, de manera que sea visualmente agradable a los usuarios.

**Comment by ChristiaanGuzman** [comment]
resuelto

**Comment by yisana** [comment]
Se realizó la prueba con una cuenta de gmail, y el mensaje llego de la siguiente manera. No se ve el logo.

![image](https://cloud.githubusercontent.com/assets/15740125/15579997/97d7af86-232c-11e6-98b6-042d5d7cf350.png)

**Comment by yisana** [comment]
Verificado
![image](https://cloud.githubusercontent.com/assets/15740125/16387106/118b6d6e-3c59-11e6-8842-52b590289878.png)
