### ISSUE TITLE
Crear página corporativa

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#11]
Caso de prueba # 88
Una vez en el formulario se especifica la información de la página corporativa y se adiciona una imagen con un tipo de archivo no permitido.

Inconsistencia

Se está realizando el proceso, pero hay que corregir ortografía en la palabra inválido del siguiente mensaje: 
![image](https://cloud.githubusercontent.com/assets/15740125/14713187/c04b9452-07a5-11e6-8e0c-06fbaf2e0729.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
Corrección verificada

![image](https://cloud.githubusercontent.com/assets/15740125/15261485/738ec178-1922-11e6-9c68-6df5c9952458.png)
