### ISSUE TITLE
Mensaje de correo electrónico - Recordar contraseña

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#110]
El mensaje actual en el correo cuando se realiza el proceso de recordar contraseña es el siguiente:

![image](https://cloud.githubusercontent.com/assets/15740125/15074711/12263bf8-1366-11e6-8640-bc215105b811.png)

Cambios a realizar:
- Coloquemos El logo de GECO de ser posible en el encabezado 
- Un titulo que diga GECO: RECUPERAR CONTRASEÑA
- Cuerpo del mensaje:
  "Hola (Nombre de la persona registrada),

Atendiendo la solicitud realizada por usted hace un momento para recuperar su contraseña, encontrará a continuación las indicaciones para generar una nueva:

Ingrese a este link e indique el siguiente usuario: (indicar el usuario) y código de seguridad (indicar el código de seguridad).

Si no ha solicitado este cambio, le sugerimos por su seguridad que realice cambio de clave.

Gracias por estar conectado a través de GECO"

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
verificado.
Por favor dejar espacios (enter) en las partes indicadas en la imagen

![image](https://cloud.githubusercontent.com/assets/15740125/15339271/3c43aaba-1c49-11e6-880e-f5182ce2d75a.png)

**Comment by yisana** [comment]
En el correo de hotmail no se está viendo el logo.
![image](https://cloud.githubusercontent.com/assets/15740125/15339537/7dabc5ae-1c4a-11e6-9aca-98116e17b985.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
verificado.

![image](https://cloud.githubusercontent.com/assets/15740125/15371935/86bb2e8c-1d03-11e6-853e-473620608f66.png)
