### ISSUE TITLE
Mensaje correo - Notificación cambio de unidad organizacional

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#111]
El mensaje que está llegando actualmente cuando se realiza un cambio de uo, es el siguiente:

![image](https://cloud.githubusercontent.com/assets/15740125/15074933/79395a7c-1367-11e6-8ed7-3fa46f7df9b9.png)

Cambios a realizar:
- Coloquemos El logo de GECO de ser posible en el encabezado.
- Un titulo que diga GECO: CAMBIO DE UNIDAD ORGANIZACIONAL
- Cuerpo del mensaje: 

"¡Cordial saludo!

(Nombre de persona registrada), queremos notificarle que el administrador de GECO ha modificado su usuario a la unidad organizacional (Nombre de la uo actual).

Gracias por su atención."

**Comment by yisana** [comment]
![image](https://cloud.githubusercontent.com/assets/15740125/15075812/e614fdb4-136b-11e6-9d57-7422aac26367.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
verificado, pero dejar espacios (enter) en los espacios indicados en la imagen.
![image](https://cloud.githubusercontent.com/assets/15740125/15339214/f1b60858-1c48-11e6-8cfc-589259310b98.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
solo se esta presentando en correos de yahoo.
