### ISSUE TITLE
Abandonar grupo - Mensaje confirmación 

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#112]
Poner tilde en la palabra está del mensaje:

![image](https://cloud.githubusercontent.com/assets/15740125/15076728/a578c330-1370-11e6-810a-97bfc04a0e31.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
verificado
![image](https://cloud.githubusercontent.com/assets/15740125/15334828/66322036-1c35-11e6-954d-b1dd685fd4b7.png)
