### ISSUE TITLE
GRUPO/PUBLICACIONES 

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#113]
Cuando se va a realizar una publicacion en un grupo, y no se ingresa texto se genera el siguiente mensaje.
![image](https://cloud.githubusercontent.com/assets/15740125/15077057/4b8dd138-1372-11e6-8b58-201f6086798b.png)

Poner tilde a la palabra publicación

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
verificado

![image](https://cloud.githubusercontent.com/assets/15740125/15332427/20c83b2a-1c2b-11e6-87c4-79e53e66d83c.png)
