### ISSUE TITLE
GRUPOS -Crear comentario a publicación

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#114]
Corregir el título del mensaje:

![image](https://cloud.githubusercontent.com/assets/15740125/15084795/8519b592-139b-11e6-825b-c3b1e4ff98ac.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
verificado

![image](https://cloud.githubusercontent.com/assets/15740125/15332347/de38bece-1c2a-11e6-8f40-bc5e4a21b35d.png)
