### ISSUE TITLE
GRUPOS - Comentarios 

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#115]
Cuando desde un grupo, se va a realizar un comentario a una publicación y no se digita nungun valor, se genera el siguiente mensaje:
![image](https://cloud.githubusercontent.com/assets/15740125/15084988/e321546e-139c-11e6-9cea-34cfb9210ebe.png)

Hay que reemplazar el texto "OK" por "ACEPTAR".

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
verificdo

![image](https://cloud.githubusercontent.com/assets/15740125/15332387/03b19f7c-1c2b-11e6-8403-ad8a73c00476.png)
