### ISSUE TITLE
GRUPOS - Comentario 

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#116]
En los grupos, cuando se crea un comentario sobre una publicación, reemplazar el texto del boton "OK", por "ACEPTAR".

![image](https://cloud.githubusercontent.com/assets/15740125/15087487/a4a79772-13ae-11e6-83ce-30497fbe0978.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
verificado
![image](https://cloud.githubusercontent.com/assets/15740125/15332305/b10898fc-1c2a-11e6-9af3-0ddf005048f5.png)
