### ISSUE TITLE
GRUPO - ELIMINAR COMENTARIO

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#117]
En el mensaje de confirmación del comentario, poner tilde en la palabra indicada en la imagen.

![image](https://cloud.githubusercontent.com/assets/15740125/15087543/5764ac74-13af-11e6-97b0-9584042696f7.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
Veriicado

![image](https://cloud.githubusercontent.com/assets/15740125/15332271/8d19a828-1c2a-11e6-8634-19fc148ae220.png)
