### ISSUE TITLE
COMENTARIO GRUPO - CON CARACTERES ESPECIALES

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#118]
Cuando desde un grupo se ingresa un comentario solo con caracteres de espaciado, se está mostrando el mensaje que el comentario ha sido enviado correctamente, pero cuando se va a consultar no esta... Debe indicarse en ese caso que: "Debe ingresar un comentario válido".

![image](https://cloud.githubusercontent.com/assets/15740125/15163817/64e288a2-16d0-11e6-8055-3fc5b3f1e9fb.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
verificado
![image](https://cloud.githubusercontent.com/assets/15740125/15332210/57f6c27a-1c2a-11e6-983d-80f61bf6f082.png)
