### ISSUE TITLE
publicaciones - grupos

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#119]
Cuando voy a crear una publicación, se muestra el mensaje de éxito, pero finalmemente queda viendose la siguiente pantalla:
![image](https://cloud.githubusercontent.com/assets/15740125/15222814/0486c3fc-1837-11e6-9085-a11049855b27.png)

Y al regresar, no se evidencia el estado que se publicó

**Comment by AndresTello** [comment]
el problema era de conexión a la base de datos.

se correige dicha conexión y se evidencia que la aplicación esta funcionando correctamente

**Comment by yisana** [comment]
ok, verificado

![image](https://cloud.githubusercontent.com/assets/15740125/15332172/31ef390e-1c2a-11e6-8b67-c3899d03e111.png)
