### ISSUE TITLE
Inactivar página corporativa

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#12]
Caso de prueba # 98
Una vez en el entorno de activación se solicita la inactivación de la página, y se espera visualizar el mensaje de confirmación de la acción y de éxito de la transacción realizada.

Inconsistencia

Se está realizando el proceso, pero hay que corregir ortografía en la palabra inactivó del siguiente mensaje: 
![image](https://cloud.githubusercontent.com/assets/15740125/14715114/4274f4d0-07ad-11e6-9059-fe1f537916f5.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
Corrección verificada
![image](https://cloud.githubusercontent.com/assets/15740125/15261535/cea7c49c-1922-11e6-8558-62c87db8cf29.png)
