### ISSUE TITLE
creacion de clasificados

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#120]
Se está permitiendo crear un clasificado sin ingresar ningún tipo de información..
Si no se ingresa titulo debe mostrar un mensaje indicando: "Ingrese titulo para el clasificado".
Si no se ingresa descripción mostrar un mensaje indicando: "Ingrese el detalle del clasificado"

![image](https://cloud.githubusercontent.com/assets/15740125/15225393/e8db7550-1843-11e6-9347-072821986fe3.png)

La palabra que aparece en ingles "New", cambiarla a español.

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
Verificado-
![image](https://cloud.githubusercontent.com/assets/15740125/15332056/bc4e24e4-1c29-11e6-827f-7e185fef22b8.png)
