### ISSUE TITLE
FOTOS DE GRUPO

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#121]
En la pantalla de fotos de grupo, cuando se va a adicionar una foto, sin haber seleccionado archivo se muestra el siguiente mensaje.

Por favor correjir el texto del botón a español "OK" cambiar por "ACEPTAR".
y poner tilde en la palabra álbum.

![image](https://cloud.githubusercontent.com/assets/15740125/15226178/4125be3e-1847-11e6-8c88-606aa6c0e883.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
verificado:
![image](https://cloud.githubusercontent.com/assets/15740125/15331926/2f746934-1c29-11e6-9838-40ef70891b91.png)
