### ISSUE TITLE
VIDEOS - GRUPOS

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#122]
cUANDO SE VA A CARGAR UN VIDEO SIN HABER ESPECIRFICADO LA URL, SE MUESTRA EL SIGUIENTE MENSAJE:
![image](https://cloud.githubusercontent.com/assets/15740125/15227188/a2105476-184b-11e6-8347-732dbd01eafd.png)

Pasar el texto del boton a español. "OK" reemplazar por "ACEPTAR"

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
verificado
![image](https://cloud.githubusercontent.com/assets/15740125/15331899/0c340aba-1c29-11e6-8ce1-0471fdd77cca.png)
