### ISSUE TITLE
videos - grupos

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#123]
Cuando un video (GRUPO)  se carga con exito, se uestra el siguiente mensaje:
![image](https://cloud.githubusercontent.com/assets/15740125/15227279/03a865c0-184c-11e6-9624-bee2c0e794a9.png)

Pasar el texto del boton a español. "OK" reemplazarlo por "ACEPTAR".

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
Corrección verificada

![image](https://cloud.githubusercontent.com/assets/15740125/15329868/f7ea6cec-1c1f-11e6-85ec-5f99ebd545ff.png)
