### ISSUE TITLE
registro - campo usuario

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#124]
En el proceso de registro, en el campo usuario debe permitirse el ingreso de caracteres alfanuméricos.

En el momento si se intenta crear un usuario que contenga números, el sistema no lo está permitiendo.

![image](https://cloud.githubusercontent.com/assets/15740125/15228499/16bdfd18-1852-11e6-8f40-cbc6ad05ec9d.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
Corrección verificada, en el formulario de registro de usuario.. Hay qeu hacer lo mismo para el formulario de registro como usuario admin.

![image](https://cloud.githubusercontent.com/assets/15740125/15329494/8fa924b2-1c1e-11e6-82fa-a2e4d341c0b7.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
Verificado en formulario de registro de usuario de admin.

![image](https://cloud.githubusercontent.com/assets/15740125/15331784/8f91a346-1c28-11e6-90e3-fe3ad5e06d17.png)
