### ISSUE TITLE
Registro de usuario

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#125]
Se ingresan los datos solicitados en el formulario de registro, y se genera el siguiente mensaje:

![image](https://cloud.githubusercontent.com/assets/15740125/15229101/22013f2a-1855-11e6-86ef-d4e51a0d2894.png)

Pero al consultar el mensaje de correo electrónico para finalizar el proceso, éste no se realiza.

**Comment by AndresTello** [comment]
el problema es de configuración.

se realiza diicha configuracion y el aplicativo esta funcionando correctamente

**Comment by yisana** [comment]
ok. verificado
