### ISSUE TITLE
Recordar contraseña

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#126]
Poner tilde en la palabra botón.

![image](https://cloud.githubusercontent.com/assets/15740125/15229497/ee42e6be-1856-11e6-8746-4f31a304308d.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
Corrección verificada.

Hay que cambiar a español (Correo electrónico)las palabras e-mail que se indica en la imagen

![image](https://cloud.githubusercontent.com/assets/15740125/15329374/20738394-1c1e-11e6-841f-9965c7ca7a76.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
Corrección verificada, sin embargo hay que modificar el texto indicado en la siguiente imagen, con el fin que sea visualmente agradable.

![image](https://cloud.githubusercontent.com/assets/15740125/15331553/76557d40-1c27-11e6-9f2c-e53480cea942.png)

**Comment by ChristiaanGuzman** [comment]
resuelto

**Comment by yisana** [comment]
Verificado
![image](https://cloud.githubusercontent.com/assets/15740125/15398426/2942eb18-1da9-11e6-9819-a1cf64cdd867.png)
