### ISSUE TITLE
Modificar álbum

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#127]
Al modificar el nombre del álbum con uno ya existente, se genera el siguiente mensaje:

![image](https://cloud.githubusercontent.com/assets/15740125/15230392/03e26f0e-185b-11e6-80a3-4f2eeb47cf67.png)

Poner tilde en la palabra álbum.

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
verificada la corrección
![image](https://cloud.githubusercontent.com/assets/15740125/15329293/c298f452-1c1d-11e6-8e60-1820f6399003.png)
