### ISSUE TITLE
Botones - efectos de color iguales

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#128]
TODOS los botones (actualmente de color verde) deben tener el mismo efecto, tanto cuando se pone el cursor sobre ellos asi como cuando no se lo pone:

Ejemplo sin pasar el mouse sobre el botón

![image](https://cloud.githubusercontent.com/assets/15740125/15230551/d9f7f4d8-185b-11e6-9e26-2eebadde5186.png)

Al pasar el mouse sobre el botón
![image](https://cloud.githubusercontent.com/assets/15740125/15230596/143bef50-185c-11e6-8399-cc4f17c2e731.png)

El color del texto de los botones no debe cambiar, siempre y cuando el botón esté en pantalla debe ser visible su contenido de una forma clara de manera que el usuario no se esfuerce. (Ya que actualmente en algunos botones la letra cambia a un gris que no se alcanza a percibir visualmente).
![image](https://cloud.githubusercontent.com/assets/15740125/15230721/cddacb8e-185c-11e6-8a4b-a14dcf3afa50.png)

Los botones identificados para aplicar las modificaciones son los indicados en el siguiente cuadro:
![image](https://cloud.githubusercontent.com/assets/15740125/15232091/83c23426-1864-11e6-941f-191cb19c2571.png)

**Comment by ChristiaanGuzman** [comment]
botones del popup eventos: se intento agregar el hover con el estilo de los demas botones pero no toma el estilo 

botones del popup en fotos se logro colocar el color de background, pero el hover no toma el estilo

botones del pop up eventos -crear eventos: tienen el color de background, pero el hover no toma el estilo

los botones del arbol de tuga todos estan con el color de background pero el hover no toma el estilo

los botones que no toman el hover se intento de diferentes maneras , en varias hojas de estilos no se identifico clases sobre escritas, ni nada por el estilo

**Comment by yisana** [comment]
Verificado en la mayoría de botones. 
Sin embargo, en los botones que se indican a continuación no hay cambios, y no están indicados en la nota con la que se resolvió el hallazgo. Favor revisar.
1. En los botones paginadores de Foros y paginas corpotativas, se está cambiando el color de la letra al pasar el cursor sobre ellos. Lo que debe cambiar es el color del botón, el texto debe permanecer visible (blanco).

FOROS
![image](https://cloud.githubusercontent.com/assets/15740125/15406188/f3d79f38-1dca-11e6-8a51-f87bf2fd6935.png)

PAGINAS CORPORATIVAS
![image](https://cloud.githubusercontent.com/assets/15740125/15406276/7aafd37c-1dcb-11e6-9291-c53f3d5fac79.png)
1. 

En los botones que aparecen en las alertas de creación de mensajes (cuando no se ingresa destinatario, y cuerpo del mensaje).  ¿Para estos 2 tampoco se logró poner el efecto al poner sobre el cursor?

Validación cuando no se ingresa destinatario.
![image](https://cloud.githubusercontent.com/assets/15740125/15406474/5d153c2a-1dcc-11e6-8dc8-6d2ddd9aa631.png)

La imagen de  la validación cuando no se ingresa mensaje no se pudo obtener ya que esta presentando un bloqueo para ingresar el destinatario.
1. En los botones de Grupos Crear y actualizar. ¿Para estos 2 tampoco se logró poner el efecto al poner sobre el cursor?

Botón crear
![image](https://cloud.githubusercontent.com/assets/15740125/15406632/e27a6e6c-1dcc-11e6-912f-28d8e174c197.png)

Botón actualizar
![image](https://cloud.githubusercontent.com/assets/15740125/15406679/14465b9a-1dcd-11e6-9371-bdbf48bc8de4.png)

**Comment by ChristiaanGuzman** [comment]
los botones de paginas y foros (paginadores) ya quedaron ajustados
pero los botones de los pop ups mencionados no toman el cambio

**Comment by yisana** [comment]
Persiste en botón paginadores de foros.
![image](https://cloud.githubusercontent.com/assets/15740125/15432160/a0feb028-1e72-11e6-93d2-a8450320850c.png)

Persiste en botón paginadores Paginas corporativas
![image](https://cloud.githubusercontent.com/assets/15740125/15432197/cf17b1da-1e72-11e6-9a6e-b05b903b8b79.png)

**Comment by yisana** [comment]
verificado.

![image](https://cloud.githubusercontent.com/assets/15740125/15434759/2b759c20-1e7e-11e6-9e9f-225f8ddde190.png)
