### ISSUE TITLE
botón - configuracion

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#129]
En la pantalla de configuración, modificar el botón de actualizar para que se vea completo. Sucede después de que se oprime ya que inicialmente se ve completo.
También se debe poner el efecto, cuando el cursor está sobre el botón.

![image](https://cloud.githubusercontent.com/assets/15740125/15295953/c09b1560-1b58-11e6-8577-a1e02e52778e.png)

**Comment by ChristiaanGuzman** [comment]
se hizo la prueba con el boton no se evidencia el hallazgo

**Comment by yisana** [comment]
Verificado.
