### ISSUE TITLE
Crear blog de noticias

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#13]
Caso de prueba # 102
Se ingresa a la opción de noticias, se especifica, la unidad organizacional, el titulo, el detalle, la etiqueta de la noticia, una imagen que se debe cargar por medio de la opcion de examinar (para obtenerla desde el equipo en el cual se está trabajando) y finalmente se solicita su publicación.

Inconsistencia
Se está realizando el proceso correctamente, pero hay que corregir ortografía en el mensaje de éxito, que se genera cuando se intenta cargar una foto.

![image](https://cloud.githubusercontent.com/assets/15740125/14715903/580a9bd0-07b0-11e6-8ba7-72e17e2786a0.png)

![image](https://cloud.githubusercontent.com/assets/15740125/14715736/95d2981a-07af-11e6-8230-bc9908a97fd8.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
corrección verificada

![image](https://cloud.githubusercontent.com/assets/15740125/15261582/287b306c-1923-11e6-9798-a2cfb753aa38.png)
