### ISSUE TITLE
Botón - Responder mensaje

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#130]
En el botón de responder mensaje, se puede editar el texto del mismo.

![image](https://cloud.githubusercontent.com/assets/15740125/15335756/58b97c02-1c39-11e6-86ce-b25d34bdfde4.png)

**Comment by ChristiaanGuzman** [comment]
resuelto

**Comment by yisana** [comment]
verificarlo, aun se puede editar.
![image](https://cloud.githubusercontent.com/assets/15740125/15395199/57125518-1d9c-11e6-9418-4af56115de83.png)

**Comment by ChristiaanGuzman** [comment]
resuelto

**Comment by yisana** [comment]
verificar. al dar clic sobre el botón se genera el siguiente mensaje:

![image](https://cloud.githubusercontent.com/assets/15740125/15397960/973c0660-1da7-11e6-8165-eae2ff3b5667.png)

**Comment by ChristiaanGuzman** [comment]
esto es desarrollo, a nivel de diseño lo que se hizo fue cambiar la propiedad input por la propiedad boton y asi el texto se dejo de editar, sim embargo es posible que ese letrero este saliendo por ese cambio. si se vuelve a colocar como input para que este letrero no salga, tocaria por medio de js ( no diseño) bloquear el input para evitar que se pueda editar

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
verificado
![image](https://cloud.githubusercontent.com/assets/15740125/15406863/d1e6806c-1dcd-11e6-93ab-de70d5c72685.png)
