### ISSUE TITLE
Notificaciones

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#131]
En la pantalla de notificaciones, cuando se va a revisarla cambiar OK por ACEPTAR.

![image](https://cloud.githubusercontent.com/assets/15740125/15360499/64681e74-1cd3-11e6-8233-36c9842e1b4b.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
verificado

![image](https://cloud.githubusercontent.com/assets/15740125/15373039/25e53eda-1d09-11e6-9de3-1ee2b1af28ee.png)
