### ISSUE TITLE
Cambio de contraseña - Mensaje error

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#132]
Cuando se intenta cambiar la contraseña y se pone una contraseña nueva diferente a la confirmación. Cambiar la palabra password por contraseña.

![image](https://cloud.githubusercontent.com/assets/15740125/15360636/061f4dc8-1cd4-11e6-871a-dc9e7a5fc014.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
verificado
![image](https://cloud.githubusercontent.com/assets/15740125/15373025/0aebaba0-1d09-11e6-918a-59cbe719932b.png)
