### ISSUE TITLE
Nombre de album - NEW

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#133]
cuando se carga fotos y no se indica nombre del album, se crea uno por defecto con nombre NEW, ver si es posible cambiar el nombre a español (nuevo).

![image](https://cloud.githubusercontent.com/assets/15740125/15362078/96b3299a-1cd9-11e6-8bee-a720bf928dc6.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
no se evidencia. favor verificar.

**Comment by AndresTello** [comment]
resuelto
se encontró que era un problema de ocnfiguración del servidor

**Comment by yisana** [comment]
verificada la corrección.
![image](https://cloud.githubusercontent.com/assets/15740125/15374711/351eebaa-1d11-11e6-8e6b-150962301d9a.png)
