### ISSUE TITLE
Invitación unirse a grupo

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#134]
Como usuario administrador, cuando se va a invitar a unirse a un grupo, aparece la opcion dee Todos, si se selecciona y se invita, el sistema  muestra un mensaje indicando que fue exitoso, pero cuando se ingresa como cualquier usuario no se ve la invitación. Quitar la opcion de todos para las invitaciones de unión a grupo.

![image](https://cloud.githubusercontent.com/assets/15740125/15362524/09e393ae-1cdb-11e6-8002-ae90fead49df.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
verificado.
![Uploading image.png…]()
