### ISSUE TITLE
Mensaje mis clasificados

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#135]
Cuando se abre la opcion de mis clasificados desde un grupo, se ve el siguiente mensaje,

cambiar a español el texto del botón.

![image](https://cloud.githubusercontent.com/assets/15740125/15362676/a983b2f4-1cdb-11e6-82a0-62e11947f5da.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
verificado.

![image](https://cloud.githubusercontent.com/assets/15740125/15372777/b7c1ced8-1d07-11e6-9b08-ddbb1d670c20.png)
