### ISSUE TITLE
Fotos - Grupo

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#136]
Cuando se crea un album con espaciados se genera el siguiente error.

![image](https://cloud.githubusercontent.com/assets/15740125/15362943/8d787f6c-1cdc-11e6-95f6-152a730e61f1.png)

**Comment by AndresTello** [comment]
resuelto.

en la creación del álbum esta funcionando correctamente, este hallazgo se corrige en la edición del álbum

**Comment by yisana** [comment]
verificado.
![image](https://cloud.githubusercontent.com/assets/15740125/15372673/2d07d7a6-1d07-11e6-82d0-98f085d032ce.png)
