### ISSUE TITLE
Album Grupos- sin nombre

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#137]
En las fotos de grupo, cuando se va a crear un album sin nombre se muestra el siguiente mensaje:
![image](https://cloud.githubusercontent.com/assets/15740125/15363006/d645652a-1cdc-11e6-8c79-5bcd79a86c2c.png)

Cambiar el texto del botón a español. Y poner la tilde en la palabra álbum donde corresponde.

**Comment by yisana** [comment]
poner las tildes en las palabras álbum, en la misma pantalla.

![image](https://cloud.githubusercontent.com/assets/15740125/15363058/0636972c-1cdd-11e6-9efc-56456af1ef35.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
verificado 
![image](https://cloud.githubusercontent.com/assets/15740125/15372718/6a87910c-1d07-11e6-9740-231b6456f4c9.png)
![image](https://cloud.githubusercontent.com/assets/15740125/15372752/91e620d8-1d07-11e6-9bc7-5ade36e94a63.png)
