### ISSUE TITLE
Fotos - grupo

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#138]
poner tilde en la palabra indicada en la imagen
![image](https://cloud.githubusercontent.com/assets/15740125/15363329/0356e40c-1cde-11e6-8425-4e57147a16fa.png)

**Comment by AndresTello** [comment]
resuelto

también se hace el cambio en los álbumes del usuario

**Comment by yisana** [comment]
verificado en álbum de grupo
![image](https://cloud.githubusercontent.com/assets/15740125/15372447/0e75fe18-1d06-11e6-99e8-3b0bfa09e0d0.png)
verificado en álbumes de usuario
![image](https://cloud.githubusercontent.com/assets/15740125/15372470/251a8152-1d06-11e6-930c-e07616fc7f27.png)
