### ISSUE TITLE
Link- miembros

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#139]
Quitar, o direccionar a donde corresponde el link de miembros en un grupo. Ver link indicado en la siguiente imagen.
![image](https://cloud.githubusercontent.com/assets/15740125/15366364/9a1b7406-1ce9-11e6-889c-8b379fb04902.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
corrección verificada.
![image](https://cloud.githubusercontent.com/assets/15740125/15372408/df75137e-1d05-11e6-914f-89391f7f6661.png)
