### ISSUE TITLE
Inactivar blog de noticias

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#14]
Caso de prueba # 109

Sobre la noticia se solicita su inactivación, visualiza el mensaje de confirmación y confirma.

Inconsistencia
Se está realizando el proceso pero hay que corregir ortografia en la palabra "inactivó" del siguiente mensaje:
![image](https://cloud.githubusercontent.com/assets/15740125/14716429/9bff1404-07b2-11e6-985e-2d3481f47882.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
Corrección verificada
![image](https://cloud.githubusercontent.com/assets/15740125/15261655/63079bd0-1923-11e6-83a8-2e6cabb1b4ba.png)
