### ISSUE TITLE
Union Grupo

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#140]
Cuando se recibe una solicitud de unión a un grupo, sin haber aceptado unirse, se puede ver todas las publicaciones del mismo. Habría que bloquear las opciones del grupo, hasta tanto el admin del grupo no haya aceptado a ese miembro.

![image](https://cloud.githubusercontent.com/assets/15740125/15367023/ba438428-1cec-11e6-8afd-70cfc9942ece.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
ok. verificado
![image](https://cloud.githubusercontent.com/assets/15740125/15400020/87fff32a-1daf-11e6-8d0e-c85761387ccf.png)
