### ISSUE TITLE
Nombrar Administador - Grupo

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#141]
Cuando se concede el permiso a un miembre de grupo a ser administrador genera el siguiente mensaje. cambiar el texto del boton a español.
![image](https://cloud.githubusercontent.com/assets/15740125/15367233/ca2fe8d0-1ced-11e6-8b2e-26e22f223f44.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
persisite. favor verificar
![image](https://cloud.githubusercontent.com/assets/15740125/15372059/38575fa8-1d04-11e6-8cef-23903ec995a1.png)

**Comment by yisana** [comment]
corrección verificada.

![image](https://cloud.githubusercontent.com/assets/15740125/15372328/8dd4af16-1d05-11e6-8d2e-642015301e51.png)
