### ISSUE TITLE
Eliminar miembro del grupo

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#142]
Cuando se elimina a un miembro de un grupo
Cambiar el texto del  botón a español.

![Uploading image.png…]()

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
persiste, favor verificar.

![image](https://cloud.githubusercontent.com/assets/15740125/15372040/1625f354-1d04-11e6-8c1d-114634d76a3b.png)

**Comment by yisana** [comment]
verificada la corrección.
![image](https://cloud.githubusercontent.com/assets/15740125/15372281/65700aa2-1d05-11e6-863b-3dbe90f7815e.png)
