### ISSUE TITLE
Mensajes - Destinatarios

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#144]
Esta bloqueado para el ingreso de destinatarios.

![image](https://cloud.githubusercontent.com/assets/15740125/15405789/0ce08546-1dc9-11e6-8ec3-35a90300171f.png)

**Comment by yisana** [comment]
Ver también mensajes de grupos, tiene el mismo inconveniente.

**Comment by AndresTello** [comment]
Se revisó la aplicación y está funcionando correctamente.

Se encontró que el texto que se digita en el buscador de usuario destinatarios no se está visualizando, para visualizarlo toca seleccionarlo

En esta imagen se digito texto en el buscador y no se visualiza:

![capture](https://cloud.githubusercontent.com/assets/15741949/15407783/584adbfe-1dd2-11e6-9ff4-5ebcc9acc4a6.PNG)

En esta imagen se selecciono el texto digitado para poder visualizarlo:

![capture2](https://cloud.githubusercontent.com/assets/15741949/15407784/584c9f84-1dd2-11e6-916b-67f1e5a61356.PNG)

**Comment by ChristiaanGuzman** [comment]
resuelto

**Comment by yisana** [comment]
No se puede evidenciar porque el boton de Nuevo mensaje no esta haciendo ninguna acción

![image](https://cloud.githubusercontent.com/assets/15740125/15431789/066df97a-1e71-11e6-93a2-7293257d8f8b.png)

**Comment by AndresTello** [comment]
se corrige el daño

**Comment by yisana** [comment]
verificado.

![image](https://cloud.githubusercontent.com/assets/15740125/15442966/31fc524c-1eaa-11e6-8a19-5ca3ebf2c6e7.png)
