### ISSUE TITLE
Videos - Carga de videos

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#146]
Cuando se va a cargar un video, al pegar la url del video no se ve el texto.
![image](https://cloud.githubusercontent.com/assets/15740125/15443054/dc44d620-1eaa-11e6-9c85-486b8c2bd658.png)

Para poder ver el texto pegado, hay que seleccionarlo
![image](https://cloud.githubusercontent.com/assets/15740125/15443070/0b00cfe6-1eab-11e6-9fa4-b7793e869623.png)

Tambien se debe verificar en la lista de usuarios. Al seleccionar una o varios UO, no se ve el texto.

**Comment by ChristiaanGuzman** [comment]
resuelto

**Comment by yisana** [comment]
verificada la corrección.

![image](https://cloud.githubusercontent.com/assets/15740125/15579592/e6a3acac-232a-11e6-8960-4c9daa94f246.png)
