### ISSUE TITLE
Pantalla inicial

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#147]
Revisar, el formulario está sobre el mapa.

![image](https://cloud.githubusercontent.com/assets/15740125/15580633/068f1124-232f-11e6-89d9-ebef68c1ed9d.png)

**Comment by ChristiaanGuzman** [comment]
resuelto

**Comment by yisana** [comment]
En mozilla aun persiste 
![image](https://cloud.githubusercontent.com/assets/15740125/16132499/f3767680-33d8-11e6-862b-e3753062ddf4.png)

**Comment by ChristiaanGuzman** [comment]
lesto

**Comment by yisana** [comment]
Ya se limpió cache y aun se evidencia. 
![image](https://cloud.githubusercontent.com/assets/15740125/16133968/4a7cdcec-33e0-11e6-9a01-24002110d1f8.png)

**Comment by ChristiaanGuzman** [comment]
falta el update seguramente de parte de sergio

![chrome](https://cloud.githubusercontent.com/assets/15741537/16134417/ab5a24be-33e2-11e6-8f56-83bbcd2b3245.png)
![mozilla](https://cloud.githubusercontent.com/assets/15741537/16134418/ab719d42-33e2-11e6-9afc-2ff4581c4ae3.png)

**Comment by yisana** [comment]
Verificado.

![image](https://cloud.githubusercontent.com/assets/15740125/16153126/97ef9dd6-346a-11e6-89da-c8657c550a0c.png)
