### ISSUE TITLE
Contenido en Creditos

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#148]
Cambiar el contenido actual de créditos por el siguiente texto:

Sitio desarrollado en el marco de la Convocatoria para el desarrollo de soluciones tecnológicas de Gobierno en Línea 663 de 2014, con el convenio FP44842-458-2014 en asocio con el Ministerio de Tecnologías de la Información y las Comunicaciones – MinTIC, el Departamento Administrativo de Ciencia, Tecnología e Innovación - COLCIENCIAS y  Illustrato Tecnologías de Información.

**NOTA: El texto debe ir subrayado de la misma manera que se muestra en la siguiente imagen:**
![image](https://cloud.githubusercontent.com/assets/15740125/16093019/c5aad3f6-32ff-11e6-92d6-6e7427aad92a.png)

**Comment by ChristiaanGuzman** [comment]
solucionado

**Comment by yisana** [comment]
Ha que corregir las letras indicadas en la siguiente imagen:
- no es tecnológicas sino tecnologías
- Cambiar "y Illustrato" por  "e Illustrato"
  ![image](https://cloud.githubusercontent.com/assets/15740125/16131731/59babc3e-33d5-11e6-8d2b-41015e2babd5.png)

![image](https://cloud.githubusercontent.com/assets/15740125/16131783/ac5317e8-33d5-11e6-9bab-881ac278b9ae.png)

**Comment by ChristiaanGuzman** [comment]
resuelto

**Comment by yisana** [comment]
Verificado.

![image](https://cloud.githubusercontent.com/assets/15740125/16133853/a68dcf88-33df-11e6-88c5-da740b158a1a.png)
