### ISSUE TITLE
Crear evento empresarial

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#15]
Caso de prueba # 112
Ubicado sobre el calendario indico la posible fecha y solicito crear evento sin especificar más información.

Inconsistencia
El proceso se está realizando correctamente, solo que hay que corregir ortografia en el siguiente mensaje: 
![image](https://cloud.githubusercontent.com/assets/15740125/14716647/804818a4-07b3-11e6-8b9c-25c91b5c3458.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
corrección verificada
![image](https://cloud.githubusercontent.com/assets/15740125/15261706/9f9f26da-1923-11e6-9d0b-e6810ce25d91.png)
