### ISSUE TITLE
Sección -Configuracion

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#150]
Modificar 
![image](https://cloud.githubusercontent.com/assets/15740125/16133235/56f5c348-33dc-11e6-8afb-158ca56c118e.png)

**Comment by ChristiaanGuzman** [comment]
resuelto

**Comment by yisana** [comment]
verificado
![image](https://cloud.githubusercontent.com/assets/15740125/16155600/b50e2c06-3475-11e6-8fb2-57a29951b4c6.png)
