### ISSUE TITLE
Cargar fotos - grupo

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#151]
cuando se escribe el nombre del album el usuario no ve el texto, hay que seleccionarlo para poder ver que fue lo que se digitó.

![image](https://cloud.githubusercontent.com/assets/15740125/16133450/7dacc7f6-33dd-11e6-9056-1f0824c0105e.png)

**Comment by ChristiaanGuzman** [comment]
resuelto

**Comment by yisana** [comment]
verificado

![image](https://cloud.githubusercontent.com/assets/15740125/16155522/7207660c-3475-11e6-8d28-783181d04043.png)
