### ISSUE TITLE
fechas documentos - Grupos

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#152]
Modificar la fecha para que quede en un solo renglón.

![image](https://cloud.githubusercontent.com/assets/15740125/16134161/527c2b68-33e1-11e6-8bd8-4c4c6e0b99ce.png)

**Comment by ChristiaanGuzman** [comment]
resuelto

**Comment by yisana** [comment]
Verificado.

![image](https://cloud.githubusercontent.com/assets/15740125/16153263/34f19666-346b-11e6-874d-ce903cd439ee.png)
