### ISSUE TITLE
Crear evento empresarial

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#16]
Caso de prueba # 116

Ubicado sobre el calendario se indica una fecha valida, se especifica el resto de la información requerida para el evento y se solicita crearlo.

Inconsistencia

Se está realizando el proceso completo, pero hay que corregir ortografía a la palabra "éxito", en el siguiente mensaje:
![image](https://cloud.githubusercontent.com/assets/15740125/14717241/29cedbae-07b6-11e6-8475-47b0e5b60a97.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
Corrección verificada.

![image](https://cloud.githubusercontent.com/assets/15740125/15261756/dd88f782-1923-11e6-9efe-56a6975f7829.png)
