### ISSUE TITLE
Editar evento empresarial

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#17]
Caso de prueba # 120
Ubicado sobre el evento modificar la fecha inicial con una fecha anterior a la actual se solicita modificar el evento.

Inconsistencia.

No esta permitiendo realzar modificación de la fecha del evento al usuario administrador.
![image](https://cloud.githubusercontent.com/assets/15740125/14720723/7ea82a38-07c8-11e6-8601-eec1ed09639d.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
corrección verificada.
