### ISSUE TITLE
Editar evento empresarial

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#18]
Caso de prueba # 121
Ubicado sobre el evento modifica el horario - selecciona la misma hora para los campos hora inicio, hora final y solicita modificar el evento.

Inconsistencia
Se esta registrando la modificación. No se muestra ningún mensaje indicando la inconsistencia. Cuando debería mostrar un mensaje que indique "La hora de finalización del evento debe ser mayor a la hora en el cual inicia". Y el sistema no debería permitir realizar la modificación.

![image](https://cloud.githubusercontent.com/assets/15740125/14720863/1b836534-07c9-11e6-9694-ed2800fb2a2c.png)

**Comment by AndresTello** [comment]
El error no se logra replicar.

Se hace una mejora en esta página para no permitir al usuario digitar nada en los campos hora inicial y final, así el usuario esta obligado a seleccionar la hora desde el control

**Comment by yisana** [comment]
corrección verificada.

![image](https://cloud.githubusercontent.com/assets/15740125/15262054/a32d56a8-1925-11e6-99f8-1f3ece4a183e.png)
