### ISSUE TITLE
enviar mensaje

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#19]
Caso de prueba # 129

En el entorno del mensaje se indica la opción enviar mensaje sin haber especificado la información. Se espera visualizar el mensaje de advertencia acerca de la información faltante.

Inconsistencia
El proceso se está realizando correctamente, solo que el botón de OK que aparece en el mensaje de alerta, no se ve muy bien. (mejorar la parte visual para el usuario)
![image](https://cloud.githubusercontent.com/assets/15740125/14723150/2f9ab4bc-07d5-11e6-9ac8-82d09d7e3d84.png)

**Comment by ChristiaanGuzman** [comment]
se evidencio el hallazgo en firefox ya fue resuelto

**Comment by yisana** [comment]
verificado.
![image](https://cloud.githubusercontent.com/assets/15740125/15398660/360edcf2-1daa-11e6-94bd-855ceb8787b8.png)
