### ISSUE TITLE
Consultar de unidad organizacional

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#2]
Caso de prueba # 13. Sobre una unidad organizacional que tenia usuarios asignados, se solicitó verlos (usuarios asociados.)

Inconsistencia: No se observa el listado de usuarios de una unidad organizacional que sí los tiene asignados. 

![image](https://cloud.githubusercontent.com/assets/15740125/14692468/06da8376-071d-11e6-8cb0-bfbc9147a4c5.png)

![image](https://cloud.githubusercontent.com/assets/15740125/14692482/21828cb4-071d-11e6-838d-1a22011e6d14.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
ok, VERIFICADO EN AMBIENTE DE RESOLUCIÓN DE HALLAZGOS.

http://prntscr.com/ayh4pu
