### ISSUE TITLE
enviar mensaje

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#20]
Caso de prueba # 130
En el entorno del mensaje se especifica la información como el destinatario, el cuerpo del mensaje y se solicita su envió. 
Se espera ver un mensaje que indique que el mensaje fue enviado con éxito, y que el mensaje sea enviado al destinatario o destinatarios indicados.

Inconsistencia.

El proceso se está realizando correctamente, solo se debe corregir la palabra 
logró (adicionar la tilde), en el mensaje que se genera al realizar el proceso.

![image](https://cloud.githubusercontent.com/assets/15740125/14723272/d14f2b94-07d5-11e6-950b-480247203bfe.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
Se verifica correción.

![image](https://cloud.githubusercontent.com/assets/15740125/15262420/d7720c86-1927-11e6-9ce2-fc55abd28a37.png)
