### ISSUE TITLE
eliminar video publicado

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#21]
Caso de prueba # 170

una vez consultado el listado de videos se debe indicar la eliminación, se confirma la solicitud.

Inconsistencia

Se está realizando el proceso de manera corercta, pero hay que corregir la palabra Eliminar en el mensaje:
![image](https://cloud.githubusercontent.com/assets/15740125/14725414/6f2bc056-07e1-11e6-964e-21902d6e7456.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
Corrección verificada.
![image](https://cloud.githubusercontent.com/assets/15740125/15293612/68415f00-1b4e-11e6-9e19-b828ac01aebe.png)
