### ISSUE TITLE
Registrar usuario

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#22]
En el momento en el que se realiza el proceso de diligenciamiento de los datos de un usuario nuevo, se está generando el siguiente mensaje que el usuario no alcanza a leer.
![image](https://cloud.githubusercontent.com/assets/15740125/14745069/315abc44-086f-11e6-92c6-3e184fd6173e.png)

Para este mensaje, hay que adicionar mas tiempo de visibilidad.

Posterior a este mensaje aparece la siguiente pantalla:

![image](https://cloud.githubusercontent.com/assets/15740125/14744871/3f3d3a5e-086e-11e6-80c6-a8639d78a507.png).

Lo anterior indica una inconsistencia, favor revisar que es lo que está sucediendo, ya que a la dirección de correo que se indicó en el formulario de registro no está llegando mensaje para continuar el proceso.

**Comment by AndresTello** [comment]
Resuelto.
Se debe agregar diseño a la página que informa cuando se intenta registrar un usuario que ya existe

**Comment by ChristiaanGuzman** [comment]
resuelto

**Comment by yisana** [comment]
verificado.
![image](https://cloud.githubusercontent.com/assets/15740125/15440334/8f8813c0-1e9a-11e6-8900-4737d8f1673f.png)
