### ISSUE TITLE
pagina de inicio

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#23]
Al seleccionar la imagen de geco, por la opcion que se indica en la siguiente imagen...

![image](https://cloud.githubusercontent.com/assets/15740125/14748346/c8280dac-087e-11e6-90f5-ab94b7bb433a.png)

se ve la siguiente pantalla

![image](https://cloud.githubusercontent.com/assets/15740125/14748367/e5116328-087e-11e6-97f5-6b4a658093f9.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
Corrección verificada.
