### ISSUE TITLE
Acceso a parametrización

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#24]
Se ingresa con el usuario khincapie con contraseña KAhi82@@ a la instancia de vijes.gecoenlinea.com, y al seleccionar la opcion de parametrización se está mostrando dos mensajes indicandole que no tiene permisos para acceder a la opción indicada.

![image](https://cloud.githubusercontent.com/assets/15740125/14748537/d4d512ba-087f-11e6-9478-949a2ba18369.png)

Favor quitar uno de los mensajes.

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
corrección verificada
![image](https://cloud.githubusercontent.com/assets/15740125/15293796/36644d7a-1b4f-11e6-9b76-2cf7c30a5c27.png)
