### ISSUE TITLE
Quitar compartir en redes sociales

### ISSUE THREAD

**Issue by popepatas** [popepatas/jeco#25]
![image](https://cloud.githubusercontent.com/assets/10553595/14786782/05fceece-0ac6-11e6-8fe4-a18412b762e5.png)

Se debe quitar los controles de compartir en redes sociales de:
- Páginas corporativas
- Noticias
- Foros
- Artículos

**Comment by yisana** [comment]
Favor OCULTAR (No quitar) los botones de acceso a redes sociales.

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
Verificado en paginas corporativas
![image](https://cloud.githubusercontent.com/assets/15740125/15295228/2f6fa0a4-1b55-11e6-866a-292c2ae15e92.png)

Verificado en noticias
![image](https://cloud.githubusercontent.com/assets/15740125/15295256/4da45f38-1b55-11e6-82d9-be47fc4fe926.png)

Verificado en foros
![image](https://cloud.githubusercontent.com/assets/15740125/15295288/5f224b30-1b55-11e6-9ef6-33a4bab055e7.png)

Verificado en artículos
![image](https://cloud.githubusercontent.com/assets/15740125/15295294/6e0d3c9a-1b55-11e6-912d-aecedbf1d086.png)
