### ISSUE TITLE
Poner uniformidad a los nombres de las UOS

### ISSUE THREAD

**Issue by popepatas** [popepatas/jeco#26]
![image](https://cloud.githubusercontent.com/assets/10553595/14786853/6f827eae-0ac6-11e6-98fb-3bf021716c7f.png)

Para evitar que se vea **"inmundo"** la diversidad de mayúsculas y minúsculas en los listados de las UOS. Modificar la pantalla de gestión de UOS para que siempre guarde el nombre de las mismas en Initcap (primera en mayúscula)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
Corrección verificada
![image](https://cloud.githubusercontent.com/assets/15740125/15295486/52f88ae4-1b56-11e6-8831-bb2707eb0ab3.png)

![image](https://cloud.githubusercontent.com/assets/15740125/15295512/7093e878-1b56-11e6-95d6-641803fc2670.png)
