### ISSUE TITLE
datos de referencia de la alcaldia

### ISSUE THREAD

**Issue by popepatas** [popepatas/jeco#27]
Se recomendó por parte de gobierno el linea, que debería tener el portal alguna página con datos de referencia de la alcaldía como una especie de acerca de nosotros pero con información de la alcaldìa y de que es Geco.

**Comment by yisana** [comment]
El texto para el home de la aplicación es:

"GEGO, es una aplicación web dirigida a entidades territoriales que buscan realizar un despliegue de  información de interés para funcionarios y ciudadanía, logrando mejoras en los canales de comunicación, y medios de participación a nivel interna (funcionarios), así como en la recepción y gestión de peticiones a nivel externo(ciudadanía)."

**Comment by ChristiaanGuzman** [comment]
resuelto a modo de pop up que se despliega del link nosotros en el footer

**Comment by yisana** [comment]
Verificado, pero hay que verificarlo nuevamente cuando se realice el cambio sugerido para el issue # 34

![image](https://cloud.githubusercontent.com/assets/15740125/15440077/0d03d03e-1e99-11e6-82be-a63fc5bcc3c6.png)

**Comment by yisana** [comment]
Revisar en chrome y en explorer, ver la imagen siguiente.
![image](https://cloud.githubusercontent.com/assets/15740125/15443479/4f5a806c-1eae-11e6-8b20-69439b36a1fe.png)

**Comment by ChristiaanGuzman** [comment]
resuelto

**Comment by yisana** [comment]
ok. verificado.
