### ISSUE TITLE
Link de geco

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#28]
En las páginas, en las que se visualice el logo de GECO, quitar el link para que no direccione a una página de error.

![image](https://cloud.githubusercontent.com/assets/15740125/14800747/63e68f84-0b09-11e6-8c68-895c7529093f.png)

página de error

![image](https://cloud.githubusercontent.com/assets/15740125/14800758/73b7dc24-0b09-11e6-82d6-c45bdf9209eb.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
ok, verificado
