### ISSUE TITLE
Formularios de registro

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#29]
En los formularios de registro y configuracion, permitir ingresar letras mayúsculas.
![image](https://cloud.githubusercontent.com/assets/15740125/14800792/d8d59510-0b09-11e6-806b-44622068032f.png)

![image](https://cloud.githubusercontent.com/assets/15740125/14800822/2e1bc04e-0b0a-11e6-9281-00d488dfaf10.png)

![image](https://cloud.githubusercontent.com/assets/15740125/14800974/55bad10c-0b0b-11e6-8747-87ad8cb7047d.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
VERIFICADO EN PANTALLA DE CONFIGURACION
![image](https://cloud.githubusercontent.com/assets/15740125/15296048/290aa49e-1b59-11e6-9d75-17c41d86794b.png)

VERIFICADO EN PANTALLA DE REGISTRO COMO ADMIN
![image](https://cloud.githubusercontent.com/assets/15740125/15299586/a9fb3120-1b6a-11e6-9529-d26406a40429.png)

VERIFICADO EN PANTALLA DE REGISTRO COMO USUARIO NORMAL
![image](https://cloud.githubusercontent.com/assets/15740125/15299686/17b1feba-1b6b-11e6-98c0-66b4afb7e2fb.png)
