### ISSUE TITLE
Registrar usuario

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#3]
Caso de prueba # 54 
En el proceso de registrar usuario, en el momento en que se recibe el correo para continuar el proceso de registro:

Ubicado en el link del cuerpo del correo enviado se solicita sea re-direccionado para continuar el registro.

Inconsistencia
Al seleccionar el link desde la bandeja de entrada del correo muestra la siguiente pantalla:
![image](https://cloud.githubusercontent.com/assets/15740125/14710405/e83f3d20-079a-11e6-934d-ecafbc1c31a6.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
Se verifica que se está direccionando a la pantalla de finalización del registro. Pero ahora, el hallazgo es que no se muestra el boton en dicho formulario.

![image](https://cloud.githubusercontent.com/assets/15740125/15260339/ea4cb3e4-191b-11e6-9bdb-2b07795befc1.png)

**Comment by AndresTello** [comment]
se revisa y el aplicativo esta funcionando correctamente

**Comment by yisana** [comment]
verificado. Pero se realiza una prueba ingresando los siguientes datos y al seleccionar la opción registrarse, no se muestra ningún mensaje (indicando que se ingrese información en los campos obligatorios, ni tampoco diciendo si se realizó o no el proceso exitosamente).

![image](https://cloud.githubusercontent.com/assets/15740125/15340628/f5fc69e6-1c4f-11e6-8e64-e640a06078ba.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
no se pudo verificar por el captcha.
![image](https://cloud.githubusercontent.com/assets/15740125/15373253/57a922a0-1d0a-11e6-85c8-5d9b4b676e28.png)

**Comment by popepatas** [comment]
listo lo del captcha

**Comment by yisana** [comment]
verificado.
