### ISSUE TITLE
Campos para el registro de usuario

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#30]
En los formularios donde se registre un usuario hay que agregar los siguientes campos

segundo nombre
segundo apellido

Igualmente hay que modificar los labels en los formularios que contengan estos datos con el nombre que corresponda (Primer nombre, segundo nombre, Primer apellido, segundo apellido)

**Comment by AndresTello** [comment]
resuelto
se le debe aplicar diseño nuevamente a la pantalla de registro, ya que el cambio que se solicito lo afecto 

![capture](https://cloud.githubusercontent.com/assets/15741949/14825859/303bcbfc-0ba1-11e6-9ff5-a3b6081b090b.PNG)

**Comment by ChristiaanGuzman** [comment]
resuelto

**Comment by yisana** [comment]
verificado.
![image](https://cloud.githubusercontent.com/assets/15740125/15398572/bee28944-1da9-11e6-8006-c34f7101f704.png)
