### ISSUE TITLE
Logos parte inferior fórmate

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#31]
Revisar la visualización de los logos  cuando se accede a fórmate

![image](https://cloud.githubusercontent.com/assets/15740125/14801134/b73be5a0-0b0c-11e6-8ddd-b38dc7545043.png)

**Comment by popepatas** [comment]
listo se ajustaron los logos. en las 3 instancias de moodle de produccion

**Comment by yisana** [comment]
verificado.
![image](https://cloud.githubusercontent.com/assets/15740125/16132782/4efb335a-33da-11e6-834a-5ce21bc37672.png)
