### ISSUE TITLE
eventos

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#32]
Al ingresar como usuario: jmarmolejo con contraseña JAma82@@ en la instancia de vijes, al ingresar los datos para crear un evento, parece que hay un problema con el formato de la fecha. Favor verificar y corregir. (validar en todas las instancias)

De acuerdo con el formato indicado,
![image](https://cloud.githubusercontent.com/assets/15740125/14827806/b897315a-0ba9-11e6-9047-dbe0f2c06599.png)

Se ingresa la fecha
![image](https://cloud.githubusercontent.com/assets/15740125/14827749/723a0070-0ba9-11e6-86fc-ca83758f90e7.png)

Y al indicar la opcion de guardar, se genera el siguiente mensaje.

![image](https://cloud.githubusercontent.com/assets/15740125/14827722/5208497e-0ba9-11e6-9484-d766a303c6b2.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
confirmada la corrección.

![image](https://cloud.githubusercontent.com/assets/15740125/15300753/e2270984-1b6f-11e6-9f9e-7ca963ea7184.png)

![image](https://cloud.githubusercontent.com/assets/15740125/15300761/ee949ca4-1b6f-11e6-8a13-6a6d61577ff8.png)
