### ISSUE TITLE
Logos, parte inferior de la página

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#34]
En la página en la parte inferior donde aparecen los logos de las diferentes entidades asociadas con el proyecto, se debe adicionar el logo de illustrato, con un texto que diga "Creado por" y para los demás logos poner un texto que diga "Créditos"

![image](https://cloud.githubusercontent.com/assets/15740125/14830192/f6b1b6f8-0bb4-11e6-89ff-5f50cc6837e3.png)

**Comment by ChristiaanGuzman** [comment]
se agrego el logo de illustrato sin embargo no se puso la palabra creditos ya que queda muy largo, y tambien falta por agregar el correo de la alcaldia correspondiente, sin embargo se entiende quien fue el creador por el created by y los demas colaboradores.

**Comment by yisana** [comment]
Modificar de acuerdo a lo sugerido en la siguiente imagen, teniendo en cuenta las indicaciones.

![image](https://cloud.githubusercontent.com/assets/15740125/15439822/b4f1084a-1e97-11e6-82e9-6ad00a50faac.png)

Incidaciones
- El texto "Creado por" debe ir en idioma español.
- La palabra nosotros, cambiarla por Contáctenos: (seguido de dos puntos: y del correo electrónico).
- La palabra Créditos si debe ir. La indicación recibida es que si no alcanza el espacio, se ponga la palabra créditos y al dar clic sobre ella se vean los logos correspondientes.

![image](https://cloud.githubusercontent.com/assets/15740125/15439678/4561d8ba-1e97-11e6-9e28-85ca930737a0.png)

**Comment by ChristiaanGuzman** [comment]
resuelto, para poder hacer que los pop up que se agregagon aparezcan en todas las paginas, se añadio los estilos de bootstrap que hacen que los pop ups funcionen, por esto fue necesario hacer un barrido al geco y ajustar las clases que el bootstrap modifico.

**Comment by yisana** [comment]
Se evidencia la modificación parcialmente.

Ha que modificar:
Created by por "Creado por"
En vez del / después de la palabra contáctenos, debe ir :
La palabra Créditos lleva tilde en la e.

![image](https://cloud.githubusercontent.com/assets/15740125/15580278/a2587a5c-232d-11e6-8a1b-dd9b35e8ffb0.png)

**Comment by ChristiaanGuzman** [comment]
resuelto

**Comment by yisana** [comment]
Verificado,
![image](https://cloud.githubusercontent.com/assets/15740125/16132631/a073a614-33d9-11e6-9005-6a7f3d0dfeb7.png)
