### ISSUE TITLE
Ver comentarios

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#36]
En la pantalla de estados, reemplazar el texto "Ver comentarios" por "Comentarios".

![image](https://cloud.githubusercontent.com/assets/15740125/14830386/0cb08c4e-0bb6-11e6-830d-a7995a36acc0.png)

**Comment by yisana** [comment]
Aplica también para las publicaciones en los grupos
![image](https://cloud.githubusercontent.com/assets/15740125/14830985/249c8dfa-0bb9-11e6-96bc-f2e1639a1eb3.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
Corrección verificada
![image](https://cloud.githubusercontent.com/assets/15740125/15300860/727290a8-1b70-11e6-8beb-ad4341b3800e.png)
