### ISSUE TITLE
Ver mas

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#37]
En las páginas siguientes quitar el texto "Ver mas", y el link que actualmente direcciona a ese ver más, sea puesto sobre el titulo.

Páginas Corporativas
Noticias
Foros
Artículos

Ejemplo
![image](https://cloud.githubusercontent.com/assets/15740125/14830673/699c064e-0bb7-11e6-988b-8974aa634b9b.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
verificado Páginas Corporativas
![image](https://cloud.githubusercontent.com/assets/15740125/15300912/bb0842a4-1b70-11e6-9a63-62253364db26.png)

Verificado Noticias
![image](https://cloud.githubusercontent.com/assets/15740125/15300934/d3055356-1b70-11e6-9462-87207615466f.png)

Verificado Foros
![image](https://cloud.githubusercontent.com/assets/15740125/15300949/e731ccce-1b70-11e6-9934-d28a21944295.png)

Verificado Artículos
![image](https://cloud.githubusercontent.com/assets/15740125/15300983/0b08bf72-1b71-11e6-9840-cc9e6595a492.png)
