### ISSUE TITLE
Invitación a grupo

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#38]
Cuando se recibe en la bandeja de entrada la invitación para acceder a un grupo, no es visible el nombre del grupo.
Verificar con el usuario khincapie contraseña: KAhi82@@

![image](https://cloud.githubusercontent.com/assets/15740125/14830784/15e29eae-0bb8-11e6-9cd5-9f65407a0f4a.png)

**Comment by AndresTello** [comment]
resuelto.

el hallazgo estaba realmente al momento de crear el grupo, permitiendo crear el grupo con el nombre con espacios y sin texto

**Comment by yisana** [comment]
verificada la corrección
