### ISSUE TITLE
Listas desplegables

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#39]
En las listas desplegables de la parametrización relación uo's, que se muestre la primera letra en Mayúscula, para que visualmente no sea desagradable como se ve en la siguiente imagen:

![image](https://cloud.githubusercontent.com/assets/15740125/14831179/1af8a576-0bba-11e6-9e5a-ac6fcff545bc.png)

**Comment by AndresTello** [comment]
Esto se resuelve con el cambio realizado en el hallazgo 26

**Comment by yisana** [comment]
Corrección verificada.
