### ISSUE TITLE
Recordar datos autenticación

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#4]
Caso de prueba # 64.
Una vez se reciba el mensaje enviado por el sistema, se ingresa el código enviado y se solicita la el cambio de contraseña, se ingresa la nueva contraseña y la confirmación de la misma y solicita almacenar el cambio.

Inconsistencia
Al seleccionar el link desde la bandeja de entrada del correo muestra la siguiente pantalla:
![image](https://cloud.githubusercontent.com/assets/15740125/14710604/a0332522-079b-11e6-8528-7e008a5c2974.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
Se revisa, y al seleccionar la opción enviar en la pantalla de recordar contraseña, se muestra lo siguiente:

![image](https://cloud.githubusercontent.com/assets/15740125/15229628/8224ed46-1857-11e6-9346-b083df5c9e2d.png)

Por lo cual no se puede verificar la solución del hallazgo

**Comment by AndresTello** [comment]
es un problema de configuración.

se realiza dicha configuración y el aplicativo esta funcionando correctamente

**Comment by yisana** [comment]
Se intentó realizar nuevamente el proceso ingresando varios correos de usuarios existentes y se está generando el siguiente mensaje:
![image](https://cloud.githubusercontent.com/assets/15740125/15261281/15ac7bfa-1921-11e6-803d-5073a07033da.png)

**Comment by AndresTello** [comment]
no se pudo replicar el error

**Comment by yisana** [comment]
verificado
