### ISSUE TITLE
Videos

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#40]
Cuando se accede a los videos como usuario administrador, en el listado de uo's se debe mostrar el o los nombres de las uo´s, no los códigos. 

Una vez corregido, direccionar a Diseño para que sea visualmente agradable.

![image](https://cloud.githubusercontent.com/assets/15740125/14831338/f62d20d6-0bba-11e6-9685-133d0dfa18af.png)

**Comment by AndresTello** [comment]
resuelto.

Se debe aplicar diseño, ya que este cambio lo afecto

**Comment by ChristiaanGuzman** [comment]
se subio un video con uos mas estos no aparecen despues de la carga

**Comment by ChristiaanGuzman** [comment]
ya

**Comment by yisana** [comment]
no se puede verificar. el boton de videos no realiza ninguna acción

![image](https://cloud.githubusercontent.com/assets/15740125/15435228/9d43da86-1e80-11e6-8ecd-f8e2aa2322b3.png)

**Comment by AndresTello** [comment]
se corrije el daño

**Comment by yisana** [comment]
verificado
![image](https://cloud.githubusercontent.com/assets/15740125/15443652/a054938a-1eaf-11e6-97bb-8448c052b668.png)
