### ISSUE TITLE
Creación de grupos - Sin nombre

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#41]
Se está permitiendo crear grupos con caracteres de espaciado. (el usuario no ve nombre de grupo). En la modificación del nombre del grupo debe verificarse que tampoco se modifique con espaciados.

![image](https://cloud.githubusercontent.com/assets/15740125/14857606/8541a9c0-0c62-11e6-9ee1-fe7fe15370ce.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
verificado
