### ISSUE TITLE
datos de contacto

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#42]
Es necesario poner en la parte inferior de cada página (Vijes, Jamundí, La Cumbre) los datos de contacto.

Asi para: Vijes:    planeacion@vijes-valle.gov.co
para: Jamundí: guillermo.benitez@jamundi-valle.gov.co
para: La Cumbre: planeacionmunicipal@lacumbre-valle.gov.co

**Comment by ChristiaanGuzman** [comment]
resuelto

**Comment by yisana** [comment]
no se evidencia
![image](https://cloud.githubusercontent.com/assets/15740125/15432439/dd438062-1e73-11e6-9524-b939352f504b.png)

**Comment by yisana** [comment]
verificado.

![image](https://cloud.githubusercontent.com/assets/15740125/15434987/5a0888da-1e7f-11e6-843f-fd2d0462431a.png)
