### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#43]
Reemplazar en: 

Páginas corporativas
Noticias
Foros
Artículos

la palabra **tags** por **palabra clave**

![image](https://cloud.githubusercontent.com/assets/15740125/14866354/eee1006c-0c88-11e6-945e-ec9356c639f0.png)

**Comment by yisana** [comment]
Tener en cuenta que en las opciones de edición, también se debe reemplazar la palabra tags por palabra clave.

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
verificado en Páginas corporativas
![image](https://cloud.githubusercontent.com/assets/15740125/15302005/34c197c6-1b76-11e6-9d11-9ff9e7aa1ef5.png)

en parte de creacion / edicion
![image](https://cloud.githubusercontent.com/assets/15740125/15302080/af8fa68c-1b76-11e6-858c-a7cff0e64caa.png)

verificado en Noticias
![image](https://cloud.githubusercontent.com/assets/15740125/15302027/57629078-1b76-11e6-9513-3aeaf6985171.png)

en parte de creacion / edicion
![image](https://cloud.githubusercontent.com/assets/15740125/15302098/cfb24064-1b76-11e6-9120-d2c209f34124.png)

verificado en Foros
![image](https://cloud.githubusercontent.com/assets/15740125/15302030/633d304c-1b76-11e6-8866-22cf2cc78b27.png)
en parte de creacion / edicion
![image](https://cloud.githubusercontent.com/assets/15740125/15302130/f8e941d0-1b76-11e6-9cf1-1875ace3110c.png)

Verificado en Artículos
![image](https://cloud.githubusercontent.com/assets/15740125/15302037/71645920-1b76-11e6-8b22-65b65d36e4d5.png)

en parte de creacion / edicion
![image](https://cloud.githubusercontent.com/assets/15740125/15302144/0b0c0b18-1b77-11e6-933e-3f669e4fea99.png)
