### ISSUE TITLE
Botón Confirmación Creación UO

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#44]
Poner tilde en el titulo del botón de confirmación al crear una uo.
![image](https://cloud.githubusercontent.com/assets/15740125/14887899/62cdd592-0d1d-11e6-892e-b630719ca091.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
verificada la corrección
![image](https://cloud.githubusercontent.com/assets/15740125/15302190/4ba58442-1b77-11e6-981e-7bb0c0bfaf76.png)
