### ISSUE TITLE
Creación de una UO con nombre nulo

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#45]
Cuando se va a crear una uo, en el campo nombre se ingresa un espaciado, y se llenan todos los campos. Al seleccionar el botón "Adicionar":
![image](https://cloud.githubusercontent.com/assets/15740125/14888206/be1284ce-0d1e-11e6-858f-867bb05bdfde.png)
1. Muestra un mensaje de confirmación de la acción a realizar. (no debe ser así. debe mostrar un mensaje indicando que "El nombre ingresado no es válido").
   ![image](https://cloud.githubusercontent.com/assets/15740125/14888248/f4a2fb2c-0d1e-11e6-9568-4e7daf40ba67.png)
2. posterior a la confirmación de creación del registro se genera el siguiente error.
   ![image](https://cloud.githubusercontent.com/assets/15740125/14888169/8c4e09cc-0d1e-11e6-9244-b269185ecb58.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
verificada la corrección
![image](https://cloud.githubusercontent.com/assets/15740125/15302229/83ea9d9c-1b77-11e6-978e-5831ff0cffec.png)
