### ISSUE TITLE
Botón confirmación de modificación de UO.

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#47]
Poner tilde en el titulo del mensaje (Confirmación).
Este mensaje se genera cuando se va a realizar modificacion a una UO.
![image](https://cloud.githubusercontent.com/assets/15740125/14888427/e330fdde-0d1f-11e6-810b-d0b6417b9567.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
verificada la corrección
![image](https://cloud.githubusercontent.com/assets/15740125/15302285/d35e8c80-1b77-11e6-9235-dbbff0d34830.png)
