### ISSUE TITLE
Creación tipo usuario con nombre espaciado

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#48]
Al adicionar un tipo de usuario ingresando en el nombre un caracter espaciado, y los demás datos obligatorios diligenciados, genera el mensaje de confirmación.

![image](https://cloud.githubusercontent.com/assets/15740125/14888915/08129f48-0d22-11e6-9f92-26cc2ca1d390.png)

Lo anterior no debe pasar, si el nombre tiene solo caracter o caracteres de espaciado, debe mostrar un mensaje que diga: "El nombre no es válido".

Ya que si se intenta crear un registro con espaciado, se está generando el siguiente error:
![image](https://cloud.githubusercontent.com/assets/15740125/14888980/614a14ce-0d22-11e6-9827-e8e0fe36e6a1.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
verificación de la corrección
![image](https://cloud.githubusercontent.com/assets/15740125/15302309/f303ef58-1b77-11e6-8195-71c41434f400.png)
