### ISSUE TITLE
Mensaje de éxito de creación de tipo usuario

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#49]
Poner tilde en el titulo del mensaje. Y cambiar el botón OK a ACEPTAR.

![image](https://cloud.githubusercontent.com/assets/15740125/14889209/6e9dddf8-0d23-11e6-981a-30393b891748.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
verificada corrección
![image](https://cloud.githubusercontent.com/assets/15740125/15302360/2b7304fa-1b78-11e6-9b8e-7c417448cb0e.png)
