### ISSUE TITLE
Acceso a aplicaciones integradas

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#5]
Caso de prueba # 64
Estando autenticado en el aplicativo, al seleccionar la aplicación integreada Fórmate, el usuario debe ser re-direccionado a la aplicación integrada sin realizar el proceso de logueo.

Inconsistencia
Al seleccionar la opcion "Entrar" en Gestion empresarial, esta visualizando la siguiente pantalla: 
![image](https://cloud.githubusercontent.com/assets/15740125/14710775/6392ba6e-079c-11e6-8562-47a50e2612cb.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
Verificado en local.
![image](https://cloud.githubusercontent.com/assets/15740125/15229858/753545da-1858-11e6-87bf-2bd643516669.png)
