### ISSUE TITLE
MENÚ IZQUIERDO - Modo comunicación

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#50]
En el menú del lado izquierdo, modificar lo siguiente:
1. Adicionar tilde en la palabra comunicación de la opción "Modos de comunicación.
2. poner con minúscula la primera letra "c" de la palabra comunicación en la opción "Modos de comunicación"
3. En la opción "Administrar usuarios" poner la letra "u" de la palabra usuarios en minúscula.
4. En la opción "Búsqueda y actualización de usuarios", poner en minúsculas la primera letra "a" de la palabra actualización, y la letra "u" de la palabra usuarios.
5. En la opción "Relacionar usuarios uos", cambiar la letra "u" de la palabra usuarios a minuscula.
6. En la opción "Administrar aplicaciones", cambiar a minúscula la primera letra "a" de la palabra aplicaciones.

![image](https://cloud.githubusercontent.com/assets/15740125/14889513/b0a8ca7c-0d24-11e6-9889-48281f9448d7.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
verificada la corrección

![image](https://cloud.githubusercontent.com/assets/15740125/15302443/9d657ad4-1b78-11e6-8dc8-1f24a454ddb9.png)
