### ISSUE TITLE
Error Modificación de uo (nombre nulo)

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#51]
Cuando se va a modificar una uo, y se pone caracter o caracteres espaciados en el nombre se genera el siguiente error:
![image](https://cloud.githubusercontent.com/assets/15740125/14891274/95c62b08-0d2b-11e6-8ea3-e21ac6f980b3.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
verificado.

![image](https://cloud.githubusercontent.com/assets/15740125/15302470/c5d7df66-1b78-11e6-98dc-1005fe3bc10d.png)
