### ISSUE TITLE
Consultar tipo de usuario

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#52]
Cuando se consulta el tipo de usuario, en el resultado arrojado de la consulta, poner tilde en la palabra descripción del detalle.

![image](https://cloud.githubusercontent.com/assets/15740125/14891997/968fe45e-0d2e-11e6-8ac6-6bd0f09bdde6.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
verificada corrección
![image](https://cloud.githubusercontent.com/assets/15740125/15302513/effc5290-1b78-11e6-89fa-b4ccccc7ea67.png)
