### ISSUE TITLE
Mensaje confirmación modificación tipo usuario

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#53]
Al tratar de modificar la informacion de un tipo de usuario, modificar la ortografia en la palabra información, y el tipo de idioma en los botones del mensaje.

OK reemplazar por ACEPTAR
CANCEL reemplazar por CANCELAR

![image](https://cloud.githubusercontent.com/assets/15740125/14892165/2e0931d2-0d2f-11e6-84a8-c350d7fb67b7.png)

**Comment by yisana** [comment]
Favor, también poner tilde en la palabra Está

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
verificada a corrección.

![image](https://cloud.githubusercontent.com/assets/15740125/15302565/26566786-1b79-11e6-8436-97eebd019ed5.png)
