### ISSUE TITLE
Botón Cancelar Modificación tipo usuario

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#54]
Cuando se va a cancelar la modificacion de un registro de tipo de usuario, corregir la ortografia (actualizó, tilde en la o) y cambiar el OK del botón  a ACEPTAR. 

![image](https://cloud.githubusercontent.com/assets/15740125/14892389/37d5dd18-0d30-11e6-84ab-44399d73dfa7.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
verificada la correcci´pn
![image](https://cloud.githubusercontent.com/assets/15740125/15302636/90a5a3c2-1b79-11e6-9bff-31ca140c1f9d.png)
