### ISSUE TITLE
Error: Modificación de tipo usuario

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#55]
Cuando se va a modificar el tipo de usuario y el campo nombre se deja nulo o se pone caracter espaciado, se muestra el siguiente mensaje:
![image](https://cloud.githubusercontent.com/assets/15740125/14892527/d0a03a52-0d30-11e6-8043-b907f56f10ee.png)

En vez del mensaje anterior, debe aparecer uno que diga: "El nombre del tipo de usuario no es válido".

También se está generando el siguiente error al darle OK al mensaje de confirmación:
![image](https://cloud.githubusercontent.com/assets/15740125/14892571/05e08e2e-0d31-11e6-8c8c-d83a02783d60.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
verificada corrección
![image](https://cloud.githubusercontent.com/assets/15740125/15302657/b61593ba-1b79-11e6-8713-cf07d33594a7.png)
