### ISSUE TITLE
Botón OK confirmación de modificación de tipo usuario

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#56]
Poner la tilde en la palabra guardó, y reemplazar el texto del botón OK por ACEPTAR.

![image](https://cloud.githubusercontent.com/assets/15740125/14893445/0cdc7c0c-0d35-11e6-8646-48cb60e699d1.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
verificada corrección
![image](https://cloud.githubusercontent.com/assets/15740125/15302693/e32e43f6-1b79-11e6-9e94-9f69a712cf44.png)
