### ISSUE TITLE
Confirmación de la eliminación de tipo de usuario

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#57]
Poner tilde en el mensaje (palabra éxito) que se genera al eliminar un tipo de usuario con éxito.

![image](https://cloud.githubusercontent.com/assets/15740125/14893826/79977efe-0d36-11e6-9d82-496fda7d4e53.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
verificada corrección

![image](https://cloud.githubusercontent.com/assets/15740125/15302730/0e29bde2-1b7a-11e6-9a1c-333299b0e2e2.png)
