### ISSUE TITLE
Cancelar solicitud de eliminación

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#58]
Poner tilde en la palabra eliminó del mensaje, y cambiar el texto OK a ACEPTAR del botón.

![image](https://cloud.githubusercontent.com/assets/15740125/14893965/fc75adc8-0d36-11e6-996a-62bda7628794.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
verificada la corrección
![image](https://cloud.githubusercontent.com/assets/15740125/15302817/8166b792-1b7a-11e6-84dc-113de6e44db3.png)
