### ISSUE TITLE
Mensaje Relación UO´S

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#59]
Corregir el mensaje que se genera cuando se va a adicionar una relación y no se ingresa Modo de comunicación. (quitar la palabra Modo), poner tilde en la palabra comunicación y reemplazar el texto del botón OK por ACEPTAR.
![image](https://cloud.githubusercontent.com/assets/15740125/14899092/1763cfa2-0d50-11e6-98fd-8f65c8176945.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
verificada corrección

![image](https://cloud.githubusercontent.com/assets/15740125/15302865/bfafda1a-1b7a-11e6-9508-ffb366e42d84.png)
