### ISSUE TITLE
Editar tipo de usuario

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#6]
Caso de prueba # 77
Se modifica el tipo de usuario pero no se ingresa información requerida (se quita el nombre). Posteriormente se selecciona la opción de "Modificar".
![image](https://cloud.githubusercontent.com/assets/15740125/14711266/541bb336-079e-11e6-82f2-2d49a83e7353.png)

Inconsistencia
Al modificar un tipo de usuario existente  y seleccionar la opción de modificar, habiendo previamente quitado todo el texto del nombre, no se está mostrando el mensaje que solicita los datos obligatorios, si no que se muestra el siguiente.

![image](https://cloud.githubusercontent.com/assets/15740125/14711305/75437f44-079e-11e6-8516-56ce62cdc119.png)

en otras ocaciones realiza el proceso normal, como si la modificación fuera exitosa, dejando en el registro los datos previos a la modificación.
![image](https://cloud.githubusercontent.com/assets/15740125/14711469/0bd248dc-079f-11e6-83f8-d0385e5d02c3.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
verificado en equipo local

![image](https://cloud.githubusercontent.com/assets/15740125/15230079/9f140f3e-1859-11e6-8d9b-9d349ebb5199.png)
