### ISSUE TITLE
Mensaje confirmación creación relación uo

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#60]
Poner tilde en la palabra Confirmación del titulo del mensaje.

![image](https://cloud.githubusercontent.com/assets/15740125/14899157/731fbe32-0d50-11e6-9446-35409199d589.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
verificada corrección

![image](https://cloud.githubusercontent.com/assets/15740125/15302902/f94622f2-1b7a-11e6-9bfa-3374e2f965c3.png)
