### ISSUE TITLE
Mensaje éxito  modificación relación uos

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#61]
Poner tilde en la palabra éxito del mensaje.

![image](https://cloud.githubusercontent.com/assets/15740125/14899598/6dbe9aba-0d52-11e6-94b1-cd2c96d82166.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
corrección verificada

![image](https://cloud.githubusercontent.com/assets/15740125/15303001/52559256-1b7b-11e6-8f4c-929e09335f5c.png)
