### ISSUE TITLE
Confirmación de carga de archivo

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#62]
Al seleccionar el archivo para cargar usuarios, en el mensaje de confirmación, poner tilde a la palabra Confirmación.

![image](https://cloud.githubusercontent.com/assets/15740125/14899862/a935392c-0d53-11e6-89ac-33c6b498901a.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
verificada la corrección
![image](https://cloud.githubusercontent.com/assets/15740125/15303158/fafe5c30-1b7b-11e6-864a-7195819043bc.png)
