### ISSUE TITLE
Relacionar usuarios a uos

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#63]
Cuando se selecciona la opcion para adicionar usuarios a una uo, y no se ha indicado el o los usuarios se está generando el siguiente mensaje:
![image](https://cloud.githubusercontent.com/assets/15740125/14901651/2c21924c-0d5c-11e6-85f0-2978498c125b.png)

Ese mensaje modificarlo por: "Debe indicar el o los usuarios a relacionar con la UO".

**Comment by AndresTello** [comment]
resuelto.

se decide cambiar el mensaje por el siguiente:
No se modificó ningún usuario de la uo seleccionada

**Comment by yisana** [comment]
verificada la corrección.

![image](https://cloud.githubusercontent.com/assets/15740125/15303221/3adf463e-1b7c-11e6-9255-f7892d2097da.png)
