### ISSUE TITLE
Botón Guardar Administrar aplicaciones

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#64]
Al ingresar a la pantalla de administrar aplicaciones, e indicar el botón guardar sin realizar ninguna otra acción, se está generando un mensaje que no coincide con el proceso a realizar. 
Favor corregirlo por el siguiente mensaje: "No se ha modificado información de aplicaciones integradas".

![image](https://cloud.githubusercontent.com/assets/15740125/14928160/e0784b72-0e1b-11e6-80ab-ca9a18ff62e4.png)

**Comment by AndresTello** [comment]
resuelto.

se decide dejar el mensaje de la siguiente forma:

Se debe seleccionar una empresa

**Comment by yisana** [comment]
al ingresar en la pantalla, se da clic sobre la lista desplegable de empresas sin escoger ninguna, y posteriormente se da clic sobre el botón guardar.
muestra el siguiente mensaje: 
![image](https://cloud.githubusercontent.com/assets/15740125/15303357/fa834a08-1b7c-11e6-9023-3900aa5ebbd5.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
verificado
![image](https://cloud.githubusercontent.com/assets/15740125/15337336/d44a8f1c-1c40-11e6-8d8d-1a5784280451.png)
