### ISSUE TITLE
Mensaje de éxito, guardar aplicaciones integradas

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#65]
Poner tilde en la palabra éxito del mensaje que se genera cuando se selecciona la opción guardar (en la pantalla inicial de aplicaciones integradas).

![image](https://cloud.githubusercontent.com/assets/15740125/14928408/6f7894de-0e1d-11e6-9aa4-949d94387485.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
corrección verificada
![image](https://cloud.githubusercontent.com/assets/15740125/15303493/b5b19438-1b7d-11e6-9347-161f1b774eba.png)
