### ISSUE TITLE
Segundo botón Guardar. Administración de aplicaciones

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#66]
En el mensaje que se genera al oprimir el segundo botón de "Guardar" de las aplicaciones integradas que se observa al seleccionar la opción de usuarios, e indicar posteriormente "si" al mensaje que indica "¿Esta seguro de guardar los cambios?", poner tilde en las palabras éxito, y guardó. Reemplazar además el texto del boton OK por ACEPTAR.

![image](https://cloud.githubusercontent.com/assets/15740125/14955544/48fc074e-1040-11e6-93eb-3efca2412ba1.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
verificada la corrección

![image](https://cloud.githubusercontent.com/assets/15740125/15303594/25488e3c-1b7e-11e6-9b78-33d873e45ad2.png)
