### ISSUE TITLE
Botón de 

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#67]
Al seleccionar la opción NO del mensaje de confirmación que se genera cuando se oprime el botón guardar (previo a la selección del botón usuarios) de la pantalla de aplicaciones integradas, no se está cerrando la pantalla, y tampoco cuando se oprime la opción cerrar en la misma pantalla.

![image](https://cloud.githubusercontent.com/assets/15740125/14955665/24e48c7c-1041-11e6-9216-b77a5f86c2da.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
corrección verificada
