### ISSUE TITLE
listas desplegables - Agregar usuario

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#68]
Las listas desplegables cuando se va a crear un usuario como admin, no están mostrando información.

![image](https://cloud.githubusercontent.com/assets/15740125/14969318/4bd193a2-1087-11e6-9a7f-3d7a30dde951.png)

**Comment by AndresTello** [comment]
se revisa la aplicación y esta funcionando correctamente.

**Comment by yisana** [comment]
Verificado.
