### ISSUE TITLE
Mensaje - Agregar usuario - Administrar usuarios

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#69]
Con la adición de campos (segundo nombre, segundo apellido), ahora se debe modificar el mensaje que se genera cuando no se ingresa información en primer apellido.
Cambiar el mensaje por algo que diga: "Escriba un valor para el campo primer apellido".

![image](https://cloud.githubusercontent.com/assets/15740125/14969435/09566114-1088-11e6-906e-2b29f58316a6.png)

**Comment by yisana** [comment]
Realizar lo mismo para el campo primer nombre, es decir.. si no se ingresa información en el primer nombre, mostrar un mensaje que indique: "Escriba un valor para el campo primer nombre".

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
verificada corrección en formulario de registro como usuario admin
![image](https://cloud.githubusercontent.com/assets/15740125/15303788/450720de-1b7f-11e6-9a8b-5cbed91fdb44.png)

![image](https://cloud.githubusercontent.com/assets/15740125/15303780/3876eebc-1b7f-11e6-95fb-6b03fc41b2bd.png)
