### ISSUE TITLE
editar tipo de usuario

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#7]
Caso de prueba # 78
Se modifica la información del tipo de usuario indicado previamente, se solicita almacenar el cambio realizado y no se confirma la acción.

Inconsistencia
El proceso se está realizando correctamente, pero se debe corregir ortografia en los siguientes mensajes: 
![image](https://cloud.githubusercontent.com/assets/15740125/14711826/7c1f6e02-07a0-11e6-9c6c-b85be20d84bd.png)

y en: 
![image](https://cloud.githubusercontent.com/assets/15740125/14711908/c50482c4-07a0-11e6-8c99-ba23039e896a.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
Verificado en equipo  local
![image](https://cloud.githubusercontent.com/assets/15740125/15230242/484d4584-185a-11e6-8f00-96cc42800f0a.png)

y 

![image](https://cloud.githubusercontent.com/assets/15740125/15230249/57bba0c4-185a-11e6-9aae-ea1ccba58b13.png)
