### ISSUE TITLE
Formulario - Administrar usuarios

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#70]
Complementar el texto en el campo "Correo", por "Correo electrónico".

![image](https://cloud.githubusercontent.com/assets/15740125/14969543/8d9019ac-1088-11e6-884f-e05e36f8d1ec.png)

Así mismo, modificar el mensaje que se genera cuando no se ingresa información en dicho campo. 
El texto debe decir: "Escriba un valor para el campo correo electrónico".

![image](https://cloud.githubusercontent.com/assets/15740125/14969583/ba5ab6fe-1088-11e6-883e-7b23fcaa83c7.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
Correccion verificada
![image](https://cloud.githubusercontent.com/assets/15740125/15303839/8ddad1d4-1b7f-11e6-8640-0a757fc4df72.png)
