### ISSUE TITLE
Error: Administrar usuarios - agregar

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#71]
Como usuario administrador (jmarmolejo), en la pantalla de agregar usuarios, se ingresó todos los datos obligatorios, menos en el campo "usuario", y al oprimir la opción de "Agregar", se generó el siguiente error:

![image](https://cloud.githubusercontent.com/assets/15740125/14985738/708eda42-110e-11e6-83c8-c298f8ac2212.png)

Si no se ingresa información de usuario, debe generarse un mensaje indicando: "Debe ingresar un valor para el campo usuario"..

**Comment by yisana** [comment]
Hay que tener en cuenta que un usuario no sea creado solo con uno o varios caracteres de espaciado. Ya que también se esta generando error.

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
verificada la corrección
![image](https://cloud.githubusercontent.com/assets/15740125/15303902/e6e1163a-1b7f-11e6-8dea-043805b8c375.png)
