### ISSUE TITLE
Mensaje de Contraseñas - Agregar usuarios

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#72]
Cuando se ingresa la información de un usuario, y no se ingresa información de contraseñas, se genera el siguiente error. Se debe modificar la palabra Password por contraseñas

![image](https://cloud.githubusercontent.com/assets/15740125/14986227/8584a3d0-1110-11e6-8762-52904b40b982.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
corregir la palabra nulas. (las contraseñas)
![image](https://cloud.githubusercontent.com/assets/15740125/15303952/352f2b6a-1b80-11e6-8cc0-220fdf6ec3d6.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
verificada la corrección.

![image](https://cloud.githubusercontent.com/assets/15740125/15325510/4239c1e0-1c10-11e6-82e1-2736d7017e3a.png)
