### ISSUE TITLE
Mensaje de éxito - Modificación usuarios

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#74]
Cuando se actualiza la informacion de un usuario, cambiar el texto del boton "OK", por "ACEPTAR".

![image](https://cloud.githubusercontent.com/assets/15740125/14986704/a62d0a30-1112-11e6-9260-a4b25534bf43.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
CORRECCION VERIFICADA
![image](https://cloud.githubusercontent.com/assets/15740125/15304765/cce44342-1b84-11e6-9b3d-785c6b6aa079.png)
