### ISSUE TITLE
INACTIVAR USUARIO

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#75]
Cuando se realiza la inactivación de un usuario, cambiar el botón del texto "OK", por "ACEPTAR".

![image](https://cloud.githubusercontent.com/assets/15740125/14986858/27c060a6-1113-11e6-87a8-6d6ebf671062.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
verificado
![image](https://cloud.githubusercontent.com/assets/15740125/15304801/1cb4c234-1b85-11e6-9314-94fce4f93cb0.png)
