### ISSUE TITLE
Cambio de contraseña como usuario admin

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#76]
Modificar todas las palabras señaladas en la imagen a español.

![image](https://cloud.githubusercontent.com/assets/15740125/14986987/d190b0ea-1113-11e6-998d-a52344aeaaff.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
faltó cambiar la palabra el passwor, ver imagen
![image](https://cloud.githubusercontent.com/assets/15740125/15304926/b6ace6b4-1b85-11e6-9bcd-9d8f2ebd1e0c.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
no se ve el cambio
![image](https://cloud.githubusercontent.com/assets/15740125/15325598/9298d3d8-1c10-11e6-98f1-2b979bd08936.png)

**Comment by AndresTello** [comment]
resuelto, se cambiaron todas las opciones de cambio de contraseña del menu.

![capture](https://cloud.githubusercontent.com/assets/15741949/15326642/6383db98-1c14-11e6-8157-96a6f844c08c.PNG)

**Comment by yisana** [comment]
verificada la corrección:

![image](https://cloud.githubusercontent.com/assets/15740125/15329172/5ee1477a-1c1d-11e6-82f1-7cd7ec089ee9.png)
