### ISSUE TITLE
Modificar mensaje de cambio de contraseña

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#77]
Cuando se ingresa como usuario admin, para cambiar contraseña, si no se ingresa correctamente se genera el siguiente mensaje:

![image](https://cloud.githubusercontent.com/assets/15740125/14987024/f9802f54-1113-11e6-9b60-73568a8919a1.png)

debe modificarse para que todo el texto del mensaje sea en español.

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
verificada la corrección

![image](https://cloud.githubusercontent.com/assets/15740125/15304996/24ca95c4-1b86-11e6-9a10-623990168592.png)
