### ISSUE TITLE
mensaje cambio contraseña

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#78]
Cuando se ingresa una contraseña anterior errada, en la pantalla de cambio de contraseña como usuario administrador, se genera el siguiente error.

Por favor actualizar el texto del mensaje todo a español.

![image](https://cloud.githubusercontent.com/assets/15740125/14987126/5fb9bd58-1114-11e6-9434-f3628bf86571.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
corrección verificada
![image](https://cloud.githubusercontent.com/assets/15740125/15305046/6bc27eb0-1b86-11e6-89bd-46a1f719f422.png)
