### ISSUE TITLE
Inconsistencia en Consulta de foros

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#80]
Cuando se ingresa a la pagina de foros, como usuario administrador, la cantidad de foros que se observa en la parte central de la pantalla, no es la mism cantidad que se indica en el consolidado qeu se muestra en la parte izquierda.

![image](https://cloud.githubusercontent.com/assets/15740125/14995383/1ad78000-113a-11e6-8ec0-bcbda142ecd4.png)

Se debe verificar por mes la cantidad real de los foros, sin importar su estado.

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
Verificada la corrección

![image](https://cloud.githubusercontent.com/assets/15740125/15325903/99ac7976-1c11-11e6-942e-ad0c32c961f0.png)
