### ISSUE TITLE
Foros inactivos

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#81]
Los foros que se están inactivando, al ser consultados por el usuario administrador, se ven con información nula

![image](https://cloud.githubusercontent.com/assets/15740125/14995714/d67d410e-113b-11e6-87e5-a0327f682783.png)

**Comment by AndresTello** [comment]
resuelto.

Se decide con sergio que solamente el AdimEcco puede ver la información de los registros que estan inactivos y para el usuario que no es adminEcco, si intenta entrar a un registro desde la url se muestra el siguiente mensaje:

"No se encontró información"

**Comment by yisana** [comment]
Verificado, pero se recomienda:
- alinear las fechas
- ponerlas con el mismo formato.

![image](https://cloud.githubusercontent.com/assets/15740125/15326424/8e3c1c34-1c13-11e6-9959-8513b95a155f.png)

**Comment by ChristiaanGuzman** [comment]
resuelto

**Comment by yisana** [comment]
no se evidencia la solución.
![image](https://cloud.githubusercontent.com/assets/15740125/15432322/63f13dee-1e73-11e6-915a-582b7a3c12e9.png)

**Comment by yisana** [comment]
verificada la justificación de fechas
![image](https://cloud.githubusercontent.com/assets/15740125/15434837/840aca68-1e7e-11e6-9a3f-870c08fe826b.png)
