### ISSUE TITLE
comentario nulos o espaciados en los foros

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#82]
Cuando se ingresa espaciados en los comentarios de los foros, se debe mostrar un mensaje indicando: "Debe ingresar un comentario válido". Esto aplica tanto para usuario administrador como para funcionarios.

![image](https://cloud.githubusercontent.com/assets/15740125/14999689/66b0bb2a-1150-11e6-9e27-f4dd0fe2519e.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
Verificado como usuario admin
![image](https://cloud.githubusercontent.com/assets/15740125/15326545/0d7864ee-1c14-11e6-8464-6b5a7435e09c.png)

Verificado como usuario funcionario.
![image](https://cloud.githubusercontent.com/assets/15740125/15326697/96ea45f8-1c14-11e6-82b8-467d6a80df7d.png)

**Comment by yisana** [comment]
se verificó la corrección con caracteres espaciados, pero cuando no se ingresa comentario y se selecciona la opción para Publicar, sin haber ingresado nada en el comentario, se está almacenando. (ver la imagen)
![image](https://cloud.githubusercontent.com/assets/15740125/15327010/9b41c576-1c15-11e6-8199-743b6cd95f0d.png)

**Comment by AndresTello** [comment]
resuelto.

el cambio se realizó en todos los blogs que contienen comentarios

**Comment by yisana** [comment]
verificado en foros
![image](https://cloud.githubusercontent.com/assets/15740125/15337176/07797746-1c40-11e6-9811-3426637021a0.png)

verificado en noticias
![image](https://cloud.githubusercontent.com/assets/15740125/15337193/21fef226-1c40-11e6-95ba-f5044e5e2d5e.png)
