### ISSUE TITLE
Nombrar fechas en foro

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#83]
Si es posible, indicar a que fecha corresponde cada una de las que se muestran en la imagen
![image](https://cloud.githubusercontent.com/assets/15740125/14999780/01099b7e-1151-11e6-8ef9-64122b5a7938.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
verificado.
![image](https://cloud.githubusercontent.com/assets/15740125/15327070/d37042c4-1c15-11e6-9f92-2bb5b7d70aa0.png)
