### ISSUE TITLE
VALORES NULOS FORO

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#84]
Está permitiendo crear foros con titulo y descripción de foros solo con caracteres espaciado, de tal forma que se observa en la consulta como se muestra en la imagen.

![image](https://cloud.githubusercontent.com/assets/15740125/15000023/550cec5c-1152-11e6-91d6-d7e31455ae79.png)

**Comment by AndresTello** [comment]
Resuelto.

Para el campo descripción no se puede hacer esta validación ya que el plugin de texto enriquecido no lo permite

**Comment by yisana** [comment]
verificado para el titulo.
![image](https://cloud.githubusercontent.com/assets/15740125/15338139/269112d4-1c44-11e6-9362-593778d50d0a.png)

verificado para descripción

![image](https://cloud.githubusercontent.com/assets/15740125/15338151/377f1e74-1c44-11e6-8b98-cbb9492016e3.png)
