### ISSUE TITLE
PUBLICAR SOBRE FOROS INACTIVOS

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#85]
Cuando el administrador, tenga inactivo un foro y vaya a realizar una publicación (comentario) sobre él, mostrar un mensaje que indique que el foro está inactivo. "El foro está inactivo".

![image](https://cloud.githubusercontent.com/assets/15740125/15017231/56845308-11da-11e6-8b49-574d20181329.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
se logró realizar la publicación sobre un foro inactivo.

![image](https://cloud.githubusercontent.com/assets/15740125/15336068/643869e8-1c3a-11e6-8fb5-17da3382c29a.png)

**Comment by AndresTello** [comment]
resuelto.

la validación se realiza para los blogs donde se permiten comentarios

**Comment by yisana** [comment]
verificado para foros
![image](https://cloud.githubusercontent.com/assets/15740125/15338040/cfe80e24-1c43-11e6-9b76-de9769946a2b.png)

verificado para noticias.
![image](https://cloud.githubusercontent.com/assets/15740125/15338091/f861465e-1c43-11e6-87b0-8cd935787f74.png)
