### ISSUE TITLE
Mensaje éxito borrar comentario en foros

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#86]
Poner tildes en las siguientes palabras del mensaje, que se genera cuando se elimina un comentario de foro:

Éxito
borró

![image](https://cloud.githubusercontent.com/assets/15740125/15018162/1a633778-11de-11e6-8e1e-95d9f99d3cae.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
ok
![image](https://cloud.githubusercontent.com/assets/15740125/15335139/a6236226-1c36-11e6-8442-787508b4eaf8.png)
