### ISSUE TITLE
Diseño pagina corporativa- tags

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#87]
Al modificarse la palabra Tag por palabra clave, se descuadró la parte visual que se observa en la siguiente imagen.

![image](https://cloud.githubusercontent.com/assets/15740125/15018556/ae5840e4-11df-11e6-9275-aa99fc14c538.png)

**Comment by ChristiaanGuzman** [comment]
resuelto

**Comment by yisana** [comment]
no se evidencia
![image](https://cloud.githubusercontent.com/assets/15740125/15432394/a5a293be-1e73-11e6-9cf4-00e1bd3a9d63.png)

**Comment by yisana** [comment]
verificado

![image](https://cloud.githubusercontent.com/assets/15740125/15434794/512cd3f2-1e7e-11e6-8727-e4b1addcdefc.png)
