### ISSUE TITLE
Páginas corporativas inactivas

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#88]
Cuando las páginas corporativas se inactivan, el usuario administrador puede verlas.
Actualmente cuando se inactiva y posteriormente el admin consulta, ve información nula para esa pagina.

![image](https://cloud.githubusercontent.com/assets/15740125/15019001/adbda262-11e1-11e6-84c3-55d6716e2eb3.png)

**Comment by AndresTello** [comment]
resuelto.

Se decide con sergio que solamente el AdimEcco puede ver la información de los registros que estan inactivos y para el usuario que no es adminEcco, si intenta entrar a un registro desde la url se muestra el siguiente mensaje:

"No se encontró información"

**Comment by yisana** [comment]
Verificado
![image](https://cloud.githubusercontent.com/assets/15740125/15336210/1239cf00-1c3b-11e6-99a1-32848076216c.png)
