### ISSUE TITLE
Consulta paginas corporativas - usuario admin

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#89]
Cuando el usuario administrador consulte las páginas corporativas, debe ver en la parte derecha, la cantidad total de paginas que ha creado. (sin importar el estado). De manera que coincida con lo consultado en la parte central.

![image](https://cloud.githubusercontent.com/assets/15740125/15019237/dea44d94-11e2-11e6-8563-deda6770a939.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
verificado.

![image](https://cloud.githubusercontent.com/assets/15740125/15336311/a3f801d2-1c3b-11e6-875f-5e24c72ebfcd.png)
