### ISSUE TITLE
NOTICIAS CON ESPACIADOS

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#90]
Si tanto en el titulo de la noticia, como en el detalle de la misma solo se ingresa caraacteres de espaciado, se debe indicar un mensaje:

"Debe ingresar un título válido para la noticia".

"Debe ingresar un detalle válido para la noticia"

![image](https://cloud.githubusercontent.com/assets/15740125/15026631/e4caa8e0-1204-11e6-96ce-c77fc358e5e6.png)

**Comment by AndresTello** [comment]
resuelto.

para el campo descripción no se puede realizar la validación ya que el editor de texto no lo permite.

**Comment by yisana** [comment]
verificado para el titulo
![image](https://cloud.githubusercontent.com/assets/15740125/15336751/a61644ea-1c3d-11e6-9409-54ad83890f6e.png)

verificado para el detalle
![image](https://cloud.githubusercontent.com/assets/15740125/15336762/b5879488-1c3d-11e6-8fb2-9557db031b6e.png)
