### ISSUE TITLE
CONSULTA DE NOTICIAS

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#91]
Como usuario administrador, al consultar las noticias, en la parte derecha debe ver la cantidad total de noticias, sin importar su estado.

![image](https://cloud.githubusercontent.com/assets/15740125/15027130/bc7e8e8a-1207-11e6-9efa-1e4a6b599213.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
ok. verificado.

![image](https://cloud.githubusercontent.com/assets/15740125/15337540/fe8c0ff2-1c41-11e6-8184-3d1fc5a54f9b.png)
