### ISSUE TITLE
Eventos - mensaje de creación

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#92]
Cuando se ingresa una fecha inferior a la fecha actual para crear un evento, se genera un mensaje que dice: "Debes seleccionar una fecha superior a la fecha actual".

Pero los eventos se pueden crear también para la fecha actual, por lo cual el mensaje hay que modificarlo de la siguiente manera:

"Debes seleccionar una fecha superior o igual a la fecha actual".

Verificar que se cumpla este mensaje en todas las opciones donde se crea eventos. ( grupos, como usuario admin).

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
verificado
![image](https://cloud.githubusercontent.com/assets/15740125/15337409/374d5b80-1c41-11e6-8abd-0d7f7f78fdce.png)
