### ISSUE TITLE
Mensaje de conformación - Creación de evento

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#93]
Cambiar de mayuscula a minuscula la letra G, de la palabra guardar.

![image](https://cloud.githubusercontent.com/assets/15740125/15027519/debe7e2c-1209-11e6-91de-aab760b30a0e.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
verificado
![image](https://cloud.githubusercontent.com/assets/15740125/15336835/1321601a-1c3e-11e6-997e-8a50ec0551fe.png)
