### ISSUE TITLE
Mensaje confirmación - eliminar video.

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#94]
Poner tilde a la palabra "Está", en el mensaje que se genera cuando se va a eliminar un video.
![image](https://cloud.githubusercontent.com/assets/15740125/15030725/afa01c30-1219-11e6-8862-a33131d233aa.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
verificado.
![image](https://cloud.githubusercontent.com/assets/15740125/15336386/03a021f0-1c3c-11e6-9ea1-b5b23fd40db4.png)
