### ISSUE TITLE
MENSAJES

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#95]
en el mensaje que se genera al querer eliminar un mensaje de los recibidos, poner tilde en la palabra está.

![image](https://cloud.githubusercontent.com/assets/15740125/15047973/efed7380-12ac-11e6-8af6-a62c1caf3ef4.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
ok
![image](https://cloud.githubusercontent.com/assets/15740125/15336227/2ecaf4b4-1c3b-11e6-925e-2a981af383aa.png)
