### ISSUE TITLE
RESPONDER -MENSAJES

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#96]
Cuando se va a responder un mensaje y se ingresa solo caracteres de espaciado se genera el siguiente mensaje:
![image](https://cloud.githubusercontent.com/assets/15740125/15048198/12687062-12ae-11e6-8c57-28b6bf99ab1b.png)

Lo que debe hacer el sistema es identificar que no se han ingresado datos validos y mostrar el siguiente mensaje: "Ingrese un mensaje válido".

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
verificado.

![image](https://cloud.githubusercontent.com/assets/15740125/15336134/af246772-1c3a-11e6-89f0-6a0c0d1db078.png)
