### ISSUE TITLE
Responder mensaje - Mensaje de éxito

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#97]
poner tilde a la palabra logró, en el mensaje que se genera cuando se responde un mensaje.

![image](https://cloud.githubusercontent.com/assets/15740125/15048334/c3003d6a-12ae-11e6-965d-bda5128d431d.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
verificado.

![image](https://cloud.githubusercontent.com/assets/15740125/15335619/b7dbb39a-1c38-11e6-81df-f513c758b063.png)
