### ISSUE TITLE
FOTOS - CARGAR IMAGEN 

### ISSUE THREAD

**Issue by yisana** [popepatas/jeco#98]
En el mensaje que se genera cuando se va a cargar una fot,  pero no se selecciona el arcihvo, se muestra el siguiente mensaje:
Se debe poner tilde en la palabra álbum, y reemplazar el texto OK por Aceptar, del botón.

![image](https://cloud.githubusercontent.com/assets/15740125/15048910/357ac692-12b1-11e6-83eb-85687c9dbd26.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by yisana** [comment]
ok
![image](https://cloud.githubusercontent.com/assets/15740125/15335372/a3a17d98-1c37-11e6-9564-74e31a71ac15.png)
